name: Validate ACR Image Exists
description: Verify that an image tag exists in Azure Container Registry before deployment

inputs:
  registry:
    description: Container registry (without .azurecr.io suffix)
    required: true
  repository:
    description: Repository name (e.g., yt-summarizer-api)
    required: true
  tag:
    description: Image tag to validate
    required: true
  fail-if-missing:
    description: Whether to fail if image doesn't exist
    required: false
    default: 'true'
  run-k8s-pull-test:
    description: Whether to attempt a Kubernetes image pull test (requires kubectl/AKS context)
    required: false
    default: 'false'

outputs:
  exists:
    description: Whether the image exists (true/false)
    value: ${{ steps.check.outputs.exists }}
  manifest-digest:
    description: Image manifest digest if exists
    value: ${{ steps.check.outputs.digest }}
  pull_success:
    description: Whether the optional k8s pull test succeeded (true/false)
    value: ${{ steps.k8s-pull-test.outputs.pull_success || '' }}

runs:
  using: composite
  steps:
    - name: Check if image exists in ACR
      id: check
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        TAG: ${{ inputs.tag }}
        FAIL_IF_MISSING: ${{ inputs.fail-if-missing }}
      run: ${{ github.action_path }}/check-acr-image.sh

    - name: Test Kubernetes image pull capability
      id: k8s-pull-test
      shell: bash
      if: ${{ steps.check.outputs.exists == 'true' && inputs.run-k8s-pull-test == 'true' }}
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        TAG: ${{ inputs.tag }}
      run: ${{ github.action_path }}/test-k8s-pull.sh
