name: 'Validate ArgoCD Application Paths'
description: 'Validates that ArgoCD Application manifests reference existing paths in the repository'
inputs:
  argocd-manifests-path:
    description: 'Path to ArgoCD application manifests (glob pattern)'
    required: false
    default: 'k8s/argocd/*.yaml'
runs:
  using: composite
  steps:
    - name: Validate Application paths
      shell: bash
      run: |
        echo "::group::Validating ArgoCD Application source paths"
        python3 -c "
        import yaml
        import os
        import sys
        import glob

        exit_code = 0
        for app_file in glob.glob('${{ inputs.argocd-manifests-path }}'):
            print(f'Checking ArgoCD Applications in: {app_file}')

            try:
                with open(app_file, 'r', encoding='utf-8') as f:
                    docs = list(yaml.safe_load_all(f))

                for doc in docs:
                    if not doc or doc.get('kind') != 'Application':
                        continue

                    app_name = doc.get('metadata', {}).get('name', 'unknown')
                    source = doc.get('spec', {}).get('source', {})
                    repo_url = source.get('repoURL', '')
                    path = source.get('path', '')

                    # Only check paths for this repo (not Helm charts)
                    if 'github.com' in repo_url and 'yt-summarizer' in repo_url and path:
                        if not os.path.exists(path):
                            print(f'❌ Application \\'{app_name}\\': path \\'{path}\\' does not exist')
                            exit_code = 1
                        else:
                            print(f'✅ Application \\'{app_name}\\': path \\'{path}\\' exists')

            except Exception as e:
                print(f'❌ Error processing {app_file}: {e}')
                exit_code = 1

        if exit_code == 0:
            print('\\n✅ All ArgoCD Application paths are valid')
        else:
            print('\\n❌ Some ArgoCD Application paths are invalid')

        sys.exit(exit_code)
        "
        echo "::endgroup::"
