name: 'Validate ArgoCD Application Paths'
description: 'Validates that ArgoCD Application manifests reference existing paths in the repository'
inputs:
  argocd-manifests-path:
    description: 'Path to ArgoCD application manifests (glob pattern)'
    required: false
    default: 'k8s/argocd/*.yaml'
runs:
  using: composite
  steps:
    - name: Validate Application paths
      shell: bash
      env:
        ARGOCD_MANIFESTS_PATH: ${{ inputs.argocd-manifests-path }}
      run: python3 ${{ github.action_path }}/validate-argocd-paths.py --manifests-path "${ARGOCD_MANIFESTS_PATH}"
