# Validate Python Dependencies
# Scans codebase for missing/unused/vulnerable dependencies
# Uses industry-standard tools: deptry, pip-audit, pipdeptree

name: 'Validate Python Dependencies'
description: 'Scan for missing dependencies, unused dependencies, and security vulnerabilities'

inputs:
  service-path:
    description: 'Path to the service directory (e.g., services/api)'
    required: true
  check-missing:
    description: 'Check for missing dependencies (imports not in pyproject.toml)'
    required: false
    default: 'true'
  check-unused:
    description: 'Check for unused dependencies (in pyproject.toml but never imported)'
    required: false
    default: 'false'
  check-security:
    description: 'Check for security vulnerabilities in dependencies'
    required: false
    default: 'true'
  fail-on-warnings:
    description: 'Fail if warnings are found'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install dependency scanning tools
      shell: bash
      run: |
        pip install deptry pip-audit pipdeptree

    - name: Display dependency tree
      shell: bash
      working-directory: ${{ inputs.service-path }}
      run: |
        echo "📦 Dependency tree:"
        pipdeptree --python $(which python) || true

    - name: Check for missing dependencies with deptry
      if: inputs.check-missing == 'true'
      shell: bash
      working-directory: ${{ inputs.service-path }}
      run: |
        echo "🔍 Scanning for missing dependencies..."
        deptry src --extend-exclude "test.*" || {
          echo "❌ MISSING DEPENDENCIES DETECTED"
          echo "Add the reported packages to pyproject.toml [project.dependencies]"
          exit 1
        }

    - name: Check for unused dependencies with deptry
      if: inputs.check-unused == 'true'
      shell: bash
      working-directory: ${{ inputs.service-path }}
      continue-on-error: ${{ inputs.fail-on-warnings == 'false' }}
      run: |
        echo "🔍 Scanning for unused dependencies..."
        deptry src --extend-exclude "test.*" --ignore-obsolete DEP004 || {
          echo "⚠️  UNUSED DEPENDENCIES DETECTED"
          echo "Consider removing unused packages from pyproject.toml"
          exit 1
        }

    - name: Check for security vulnerabilities with pip-audit
      if: inputs.check-security == 'true'
      shell: bash
      working-directory: ${{ inputs.service-path }}
      continue-on-error: ${{ inputs.fail-on-warnings == 'false' }}
      run: |
        echo "🔒 Scanning for security vulnerabilities..."
        pip-audit --require-hashes --desc --skip-editable || {
          echo "⚠️  SECURITY VULNERABILITIES DETECTED"
          echo "Review and update vulnerable packages"
          exit 1
        }

    - name: Summary
      shell: bash
      run: |
        echo "✅ Dependency validation complete"
        echo "Checks performed:"
        echo "  - Missing dependencies: ${{ inputs.check-missing }}"
        echo "  - Unused dependencies: ${{ inputs.check-unused }}"
        echo "  - Security vulnerabilities: ${{ inputs.check-security }}"
