name: Update Preview Overlay
description: Update Kubernetes preview overlay with image tags and preview configuration

inputs:
  pr-number:
    description: Pull request number
    required: true
  image-tag:
    description: Docker image tag to use
    required: true
  acr-server:
    description: Azure Container Registry server
    required: true
  preview-host:
    description: Preview environment hostname
    required: true
  tls-secret:
    description: TLS secret name
    required: true
  preview-url:
    description: Full preview URL
    required: true
  commit-sha:
    description: Current commit SHA to ensure overlay always changes
    required: true

outputs:
  preview_url:
    description: Preview environment URL
    value: ${{ steps.generate.outputs.preview_url }}
  preview_host:
    description: Preview environment host
    value: ${{ steps.generate.outputs.preview_host }}
  tls_secret:
    description: TLS secret name
    value: ${{ steps.generate.outputs.tls_secret }}

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.image-tag }}" ]; then
          echo "::error::IMAGE_TAG is empty. Aborting to avoid committing empty tags."
          exit 1
        fi
        
        OVERLAY_FILE="k8s/overlays/preview/kustomization.yaml"
        if [ ! -f "$OVERLAY_FILE" ]; then
          echo "::error::Preview overlay not found at ${OVERLAY_FILE}"
          echo "::error::Ensure k8s/overlays/preview/ exists in your PR branch"
          exit 1
        fi

    - name: Generate preview overlay
      id: generate
      shell: bash
      run: |
        OVERLAY_FILE="k8s/overlays/preview/kustomization.yaml"
        
        echo "Using IMAGE_TAG=${{ inputs.image-tag }}"
        
        # Update image tags in kustomization.yaml using Python script
        python scripts/ci/generate_preview_kustomization.py \
          --template scripts/ci/templates/preview-kustomization-template.yaml \
          --output "$OVERLAY_FILE" \
          --pr-number "${{ inputs.pr-number }}" \
          --image-tag "${{ inputs.image-tag }}" \
          --acr-server "${{ inputs.acr-server }}" \
          --preview-host "${{ inputs.preview-host }}" \
          --tls-secret "${{ inputs.tls-secret }}" \
          --commit-sha "${{ inputs.commit-sha }}"
        
        echo "✅ Updated preview overlay at ${OVERLAY_FILE}"
        
        # Output values for downstream jobs
        echo "preview_url=${{ inputs.preview-url }}" >> $GITHUB_OUTPUT
        echo "preview_host=${{ inputs.preview-host }}" >> $GITHUB_OUTPUT
        echo "tls_secret=${{ inputs.tls-secret }}" >> $GITHUB_OUTPUT
        
        # Display generated overlay for verification
        cat "$OVERLAY_FILE"
