name: Update Preview Overlay
description: Update Kubernetes preview overlay with image tags and preview configuration

inputs:
  pr-number:
    description: Pull request number
    required: true
  image-tag:
    description: Docker image tag to use
    required: true
  acr-server:
    description: Azure Container Registry server
    required: true
  preview-host:
    description: Preview environment hostname
    required: true
  tls-secret:
    description: TLS secret name
    required: true
  preview-url:
    description: Full preview URL
    required: true
  commit-sha:
    description: Current commit SHA to ensure overlay always changes
    required: true

outputs:
  preview_url:
    description: Preview environment URL
    value: ${{ steps.generate.outputs.preview_url }}
  preview_host:
    description: Preview environment host
    value: ${{ steps.generate.outputs.preview_host }}
  tls_secret:
    description: TLS secret name
    value: ${{ steps.generate.outputs.tls_secret }}

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        if [ -z "${IMAGE_TAG}" ]; then
          echo "::error::IMAGE_TAG is empty. Aborting to avoid committing empty tags."
          exit 1
        fi

        OVERLAY_FILE="k8s/overlays/preview/kustomization.yaml"
        if [ ! -f "${OVERLAY_FILE}" ]; then
          echo "::error::Preview overlay not found at ${OVERLAY_FILE}"
          echo "::error::Ensure k8s/overlays/preview/ exists in your PR branch"
          exit 1
        fi

    - name: Generate preview overlay
      id: generate
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        ACR_SERVER: ${{ inputs.acr-server }}
        PREVIEW_HOST: ${{ inputs.preview-host }}
        TLS_SECRET: ${{ inputs.tls-secret }}
        PREVIEW_URL: ${{ inputs.preview-url }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
      run: bash ${{ github.action_path }}/script.sh
