name: 'Compute Preview URLs'
description: 'Computes preview environment URLs based on PR number using Gateway API with wildcard DNS'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  app-name:
    description: 'Application name'
    required: false
    default: 'yt-summarizer'
  base-domain:
    description: 'Base domain for previews'
    required: false
    default: 'yt-summarizer.apps.ashleyhollis.com'

outputs:
  preview-url:
    description: 'Full preview URL (e.g., https://api-pr-123.yt-summarizer.apps.ashleyhollis.com)'
    value: ${{ steps.compute.outputs.preview_url }}
  preview-host:
    description: 'Preview hostname (e.g., api-pr-123.yt-summarizer.apps.ashleyhollis.com)'
    value: ${{ steps.compute.outputs.preview_host }}
  tls-secret:
    description: 'TLS secret name for preview (shared wildcard certificate)'
    value: ${{ steps.compute.outputs.tls_secret }}
  namespace:
    description: 'Preview namespace'
    value: ${{ steps.compute.outputs.namespace }}

runs:
  using: composite
  steps:
    - name: Compute URLs
      id: compute
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        APP_NAME: ${{ inputs.app-name }}
        BASE_DOMAIN: ${{ inputs.base-domain }}
      run: ${{ github.action_path }}/compute-preview-urls.sh
