name: 'Compute Preview URLs'
description: 'Computes preview environment URLs based on PR number using Gateway API with wildcard DNS'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  app-name:
    description: 'Application name'
    required: false
    default: 'yt-summarizer'
  base-domain:
    description: 'Base domain for previews'
    required: false
    default: 'yt-summarizer.apps.ashleyhollis.com'

outputs:
  preview-url:
    description: 'Full preview URL (e.g., https://api-pr-123.yt-summarizer.apps.ashleyhollis.com)'
    value: ${{ steps.compute.outputs.preview_url }}
  preview-host:
    description: 'Preview hostname (e.g., api-pr-123.yt-summarizer.apps.ashleyhollis.com)'
    value: ${{ steps.compute.outputs.preview_host }}
  tls-secret:
    description: 'TLS secret name for preview (shared wildcard certificate)'
    value: ${{ steps.compute.outputs.tls_secret }}
  namespace:
    description: 'Preview namespace'
    value: ${{ steps.compute.outputs.namespace }}

runs:
  using: composite
  steps:
    - name: Compute URLs
      id: compute
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        APP_NAME: ${{ inputs.app-name }}
        BASE_DOMAIN: ${{ inputs.base-domain }}
      run: |
        # New URL scheme uses Gateway API with wildcard DNS
        # Format: api-pr-{number}.{base-domain}
        # Example: api-pr-123.yt-summarizer.apps.ashleyhollis.com

        # Compute preview hostname
        PREVIEW_HOST="api-pr-${PR_NUMBER}.${BASE_DOMAIN}"

        # Preview URL (always HTTPS with wildcard certificate)
        PREVIEW_URL="https://${PREVIEW_HOST}"

        # TLS secret name (shared wildcard certificate from gateway-system namespace)
        # Note: Gateway terminates TLS, no per-preview secret needed
        TLS_SECRET="yt-summarizer-wildcard-tls"

        # Namespace
        NAMESPACE="preview-pr-${PR_NUMBER}"

        echo "preview_url=${PREVIEW_URL}" >> $GITHUB_OUTPUT
        echo "preview_host=${PREVIEW_HOST}" >> $GITHUB_OUTPUT
        echo "tls_secret=${TLS_SECRET}" >> $GITHUB_OUTPUT
        echo "namespace=${NAMESPACE}" >> $GITHUB_OUTPUT

        echo "✅ Preview URLs computed:"
        echo "   URL: ${PREVIEW_URL}"
        echo "   Host: ${PREVIEW_HOST}"
        echo "   TLS Secret: ${TLS_SECRET} (shared wildcard)"
        echo "   Namespace: ${NAMESPACE}"
