name: Build Images
description: Build and push a single Docker image for a service

inputs:
  service:
    description: The service to build (api, workers, shared)
    required: true
  image-tag:
    description: The image tag to use
    required: true
  push:
    description: Whether to push images to registry (false for validation only)
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker

    - name: Build image
      shell: bash
      env:
        SERVICE: ${{ inputs.service }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        PUSH_FLAG: ${{ inputs.push }}
      run: bash ${{ github.action_path }}/script.sh
