name: 'Create Cleanup Summary'
description: 'Creates a GitHub Actions step summary for preview cleanup'
inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  pr-merged:
    description: 'Whether the PR was merged (true/false)'
    required: true
runs:
  using: composite
  steps:
    - name: Create cleanup summary
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        PR_MERGED: ${{ inputs.pr-merged }}
      run: bash ${{ github.action_path }}/script.sh
