name: Post E2E Test Results
description: Post or update E2E test results comment on PR with detailed information

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  pr-number:
    description: Pull request number
    required: true
  test-outcome:
    description: Test outcome (success/failure)
    required: true
  preview-url:
    description: Preview environment URL where tests ran
    required: true
  commit-sha:
    description: Commit SHA tested
    required: true
  run-id:
    description: GitHub Actions run ID
    required: true
  repository:
    description: GitHub repository (owner/repo)
    required: true

runs:
  using: composite
  steps:
    - name: Post/update E2E results comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const outcome = '${{ inputs.test-outcome }}';
          const isSuccess = outcome === 'success';
          const status = isSuccess ? '✅ All Tests Passed' : '❌ Tests Failed';
          const emoji = isSuccess ? '✅' : '❌';
          const headerEmoji = isSuccess ? '🎉' : '⚠️';
          const reportUrl = `https://github.com/${{ inputs.repository }}/actions/runs/${{ inputs.run-id }}`;
          const artifactUrl = `https://github.com/${{ inputs.repository }}/actions/runs/${{ inputs.run-id }}#artifacts`;
          const commitSha = '${{ inputs.commit-sha }}';

          let body = `## ${headerEmoji} E2E Test Results\n\n`;

          if (isSuccess) {
            body += `All end-to-end tests passed successfully! ✨\n\n`;
          } else {
            body += `Some tests failed. Please review the test report for details.\n\n`;
          }

          body += `### 📊 Test Summary\n\n` +
            `| Property | Value |\n` +
            `|----------|-------|\n` +
            `| **Status** | ${status} |\n` +
            `| **Environment** | [${{ inputs.preview-url }}](${{ inputs.preview-url }}) |\n` +
            `| **Commit** | [\`${commitSha.substring(0, 7)}\`](https://github.com/${{ inputs.repository }}/commit/${commitSha}) |\n\n`;

          body += `### 🔗 Reports & Artifacts\n\n` +
            `- 📋 [View Workflow Logs](${reportUrl})\n` +
            `- 📦 [Download Playwright Report](${artifactUrl})\n\n`;

          if (!isSuccess) {
            body += `### 🔍 Debugging Tips\n\n` +
              `<details>\n` +
              `<summary>Click to expand troubleshooting steps</summary>\n\n` +
              `1. **Download the Playwright report** from the artifacts link above\n` +
              `2. **Check the test logs** in the workflow run for specific failures\n` +
              `3. **Verify the preview environment** is healthy:\n` +
              `   \`\`\`bash\n` +
              `   curl -s ${{ inputs.preview-url }}/health/ready | jq\n` +
              `   \`\`\`\n` +
              `4. **Run tests locally** with:\n` +
              `   \`\`\`bash\n` +
              `   cd apps/web\n` +
              `   USE_EXTERNAL_SERVER=true BASE_URL=${{ inputs.preview-url }} npx playwright test\n` +
              `   \`\`\`\n` +
              `</details>\n\n`;
          }

          body += `---\n_E2E tests run on every preview deployment to catch integration issues early._`;

          // Find existing E2E comment to update
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.pr-number }},
          });

          const e2eComment = comments.find(c =>
            c.user.type === 'Bot' &&
            c.body.includes('E2E Test Results')
          );

          if (e2eComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: e2eComment.id,
              body: body
            });
            console.log('Updated existing E2E comment');
          } else {
            await github.rest.issues.createComment({
              issue_number: ${{ inputs.pr-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
            console.log('Created new E2E comment');
          }

    - name: Create E2E summary
      shell: bash
      env:
        TEST_OUTCOME: ${{ inputs.test-outcome }}
        PREVIEW_URL: ${{ inputs.preview-url }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
      run: ${{ github.action_path }}/post-e2e-results.sh
