name: Cleanup Image Pull Secrets
description: Delete docker-registry imagePull secrets from preview namespaces (safe, targets preview-pr-*)

inputs:
  pr-number:
    description: PR number to target (optional)
    required: false
  namespace:
    description: Specific namespace to target (optional)
    required: false
  secret-names:
    description: Comma-separated secret names to target (optional). Defaults to all docker-registry secrets in namespace.
    required: false

runs:
  using: composite
  steps:
    - name: Delete docker-registry secrets from preview namespaces
      id: delete
      shell: bash
      run: |
        set -euo pipefail

        PR_NUMBER="${{ inputs.pr-number }}"
        NAMESPACE_INPUT="${{ inputs.namespace }}"
        SECRET_NAMES_INPUT="${{ inputs.secret-names }}"

        echo "🔍 Cleanup Image Pull Secrets"

        # Determine target namespaces
        NAMESPACES=()
        if [ -n "$NAMESPACE_INPUT" ]; then
          NAMESPACES=("$NAMESPACE_INPUT")
        elif [ -n "$PR_NUMBER" ]; then
          NAMESPACES=("preview-pr-$PR_NUMBER")
        else
          # Find all preview namespaces
          mapfile -t NAMESPACES < <(kubectl get ns -o jsonpath='{.items[*].metadata.name}' 2>/dev/null | tr ' ' '\n' | grep '^preview-pr-' || true)
        fi

        if [ ${#NAMESPACES[@]} -eq 0 ]; then
          echo "No preview namespaces found; nothing to clean." >&2
          echo "deleted-count=0" >> $GITHUB_OUTPUT
          echo "deleted-secrets=" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Target namespaces: ${NAMESPACES[*]}"

        DELETED=()

        for ns in "${NAMESPACES[@]}"; do
          echo "Checking namespace: $ns"

          # Safety: don't operate outside preview namespaces
          if [[ ! "$ns" =~ ^preview-pr- ]]; then
            echo "Skipping non-preview namespace: $ns" >&2
            continue
          fi

          # Find dockerconfigjson secrets
          mapfile -t secrets < <(kubectl get secret -n "$ns" -o json 2>/dev/null | jq -r '.items[] | select(.type=="kubernetes.io/dockerconfigjson") | .metadata.name' || true)

          if [ -n "$SECRET_NAMES_INPUT" ]; then
            # Filter by given names
            IFS=',' read -ra WANT <<< "$SECRET_NAMES_INPUT"
            FILTERED=()
            for s in "${secrets[@]}"; do
              for want in "${WANT[@]}"; do
                if [ "$s" = "$want" ]; then
                  FILTERED+=("$s")
                fi
              done
            done
            secrets=("${FILTERED[@]}")
          fi

          if [ ${#secrets[@]} -eq 0 ]; then
            echo "  No docker-registry secrets found in $ns"
            continue
          fi

          for s in "${secrets[@]}"; do
            echo "  Deleting secret: $s (namespace: $ns)"
            kubectl delete secret "$s" -n "$ns" --ignore-not-found=true || true
            DELETED+=("$ns/$s")
          done
        done

        DELETED_COUNT=${#DELETED[@]}
        echo "Deleted $DELETED_COUNT secret(s): ${DELETED[*]}"

        echo "deleted-count=${DELETED_COUNT}" >> $GITHUB_OUTPUT
        echo "deleted-secrets=${DELETED[*]}" >> $GITHUB_OUTPUT
