name: Verify Deployment Image
description: Verify that a Kubernetes deployment is using the expected image tag

inputs:
  namespace:
    description: Kubernetes namespace
    required: true
  deployment-name:
    description: Name of the deployment to verify
    required: true
  expected-tag:
    description: Expected image tag
    required: true
  registry:
    description: Container registry
    required: true
  image-name:
    description: Image name (without registry prefix)
    required: true
  timeout-seconds:
    description: Maximum time to wait in seconds
    required: false
    default: '300'
  wait-for-ready:
    description: Wait for deployment to be ready
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Verify deployment image
      shell: bash
      run: |
        export INPUT_NAMESPACE="${{ inputs.namespace }}"
        export INPUT_DEPLOYMENT_NAME="${{ inputs.deployment-name }}"
        export INPUT_EXPECTED_TAG="${{ inputs.expected-tag }}"
        export INPUT_REGISTRY="${{ inputs.registry }}"
        export INPUT_IMAGE_NAME="${{ inputs.image-name }}"
        export INPUT_TIMEOUT_SECONDS="${{ inputs.timeout-seconds }}"
        export INPUT_WAIT_FOR_READY="${{ inputs.wait-for-ready }}"

        cd "${{ github.action_path }}" && bash script.sh
