name: Verify Deployment Image
description: Verify that a Kubernetes deployment is using the expected image tag

inputs:
  namespace:
    description: Kubernetes namespace
    required: true
  deployment-name:
    description: Name of the deployment to verify
    required: true
  expected-tag:
    description: Expected image tag
    required: true
  registry:
    description: Container registry
    required: true
  image-name:
    description: Image name (without registry prefix)
    required: true
  app-name:
    description: Argo CD application name (for pre-sync validation)
    required: false
  timeout-seconds:
    description: Maximum time to wait in seconds
    required: false
    default: '300'
  wait-for-ready:
    description: Wait for deployment to be ready
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Verify deployment image
      shell: bash
      env:
        INPUT_NAMESPACE: ${{ inputs.namespace }}
        INPUT_DEPLOYMENT_NAME: ${{ inputs.deployment-name }}
        INPUT_EXPECTED_TAG: ${{ inputs.expected-tag }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_IMAGE_NAME: ${{ inputs.image-name }}
        INPUT_APP_NAME: ${{ inputs.app-name }}
        INPUT_TIMEOUT_SECONDS: ${{ inputs.timeout-seconds }}
        INPUT_WAIT_FOR_READY: ${{ inputs.wait-for-ready }}
      run: bash ${{ github.action_path }}/script.sh
