name: Run Playwright Tests
description: Installs Playwright browsers and runs E2E tests

inputs:
  working-directory:
    description: Directory containing Playwright tests
    required: false
    default: 'apps/web'
  playwright-args:
    description: Additional Playwright test arguments
    required: false
    default: '--reporter=html'
  install-deps:
    description: Install system dependencies with browsers
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install and run Playwright tests
      shell: bash
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INSTALL_DEPS: ${{ inputs.install-deps }}
        PLAYWRIGHT_ARGS: ${{ inputs.playwright-args }}
      run: bash ${{ github.action_path }}/script.sh
