name: Run Playwright Tests
description: Installs Playwright browsers and runs E2E tests

inputs:
  working-directory:
    description: Directory containing Playwright tests
    required: false
    default: 'apps/web'
  playwright-args:
    description: Additional Playwright test arguments
    required: false
    default: '--reporter=html'
  install-deps:
    description: Install system dependencies with browsers
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Restore Playwright browser cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: >-
          ${{ runner.os }}-playwright-
          ${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - name: Install and run Playwright tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INSTALL_DEPS: ${{ inputs.install-deps }}
        PLAYWRIGHT_ARGS: ${{ inputs.playwright-args }}
      run: bash ${{ github.action_path }}/script.sh
