name: Commit Overlay Changes
description: Commit and push Kubernetes overlay changes to PR branch

inputs:
  pr-number:
    description: Pull request number
    required: true
  image-tag:
    description: Docker image tag used
    required: true
  commit-sha:
    description: Commit SHA being deployed
    required: true
  pr-branch:
    description: PR branch name
    required: true

runs:
  using: composite
  steps:
    - name: Commit and push overlay update
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Sanity: ensure generated overlay contains a non-empty newTag
        if grep -q "newTag: \"\"" k8s/overlays/preview/kustomization.yaml; then
          echo "::error::Generated overlay has empty newTag - aborting commit"
          echo "--- overlay ---"
          cat k8s/overlays/preview/kustomization.yaml
          echo "--- end overlay ---"
          exit 1
        fi

        git add k8s/overlays/preview/

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore(preview): update image tags for PR #${{ inputs.pr-number }}

          Image tag: ${{ inputs.image-tag }}
          Commit: ${{ inputs.commit-sha }}

          [skip ci]"

          git push origin ${{ inputs.pr-branch }}
          echo "✅ Pushed overlay changes to ${{ inputs.pr-branch }}"
        fi
