name: Commit Overlay Changes
description: Commit and push Kubernetes overlay changes to PR branch

inputs:
  pr-number:
    description: Pull request number
    required: true
  image-tag:
    description: Docker image tag used
    required: true
  commit-sha:
    description: Commit SHA being deployed
    required: true
  pr-branch:
    description: PR branch name
    required: true

runs:
  using: composite
  steps:
    - name: Commit and push overlay update
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        PR_BRANCH: ${{ inputs.pr-branch }}
      run: ${{ github.action_path }}/commit-overlay.sh
