name: Wait for Argo CD
description: Wait for Argo CD to sync and create/update the environment
# Renamed from: wait-for-argocd-sync (for naming consistency)

inputs:
  app-name:
    description: Argo CD application name (e.g., "yt-summarizer-prod" or "preview-pr-123")
    required: true
  namespace:
    description: Kubernetes namespace to wait for
    required: true
  pr-number:
    description: Pull request number (for diagnostics, use "0" for production)
    required: true
  timeout-seconds:
    description: Maximum time to wait in seconds
    required: false
    default: '180'

runs:
  using: composite
  steps:
    - name: Wait for Argo CD sync and gather diagnostics
      shell: bash
      env:
        APP_NAME: ${{ inputs.app-name }}
        NAMESPACE: ${{ inputs.namespace }}
        PR_NUMBER: ${{ inputs.pr-number }}
        TIMEOUT_SECONDS: ${{ inputs.timeout-seconds }}
        INTERVAL: 5
      run: bash ${{ github.action_path }}/script.sh
