name: Emit PR Metadata
description: Extract and emit PR metadata for workflow use

outputs:
  pr_number:
    description: Pull request number
    value: ${{ steps.emit.outputs.pr_number }}
  pr_head_ref:
    description: PR head branch reference
    value: ${{ steps.emit.outputs.pr_head_ref }}
  pr_head_sha:
    description: PR head commit SHA
    value: ${{ steps.emit.outputs.pr_head_sha }}

runs:
  using: composite
  steps:
    - name: Emit PR metadata
      id: emit
      shell: bash
      run: |
        echo "pr_number=${{ github.event.pull_request.number || github.event.workflow_run.pull_requests[0].number }}" >> $GITHUB_OUTPUT
        echo "pr_head_ref=${{ github.event.pull_request.head.ref || github.event.workflow_run.pull_requests[0].head.ref }}" >> $GITHUB_OUTPUT
        echo "pr_head_sha=${{ github.event.pull_request.head.sha || github.event.workflow_run.pull_requests[0].head.sha }}" >> $GITHUB_OUTPUT
