name: Emit PR Metadata
description: Extract and emit PR metadata for workflow use

outputs:
  pr_number:
    description: Pull request number
    value: ${{ steps.emit.outputs.pr_number }}
  pr_head_ref:
    description: PR head branch reference
    value: ${{ steps.emit.outputs.pr_head_ref }}
  pr_head_sha:
    description: PR head commit SHA
    value: ${{ steps.emit.outputs.pr_head_sha }}

runs:
  using: composite
  steps:
    - name: Emit PR metadata
      id: emit
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.workflow_run.pull_requests[0].number }}
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref || github.event.workflow_run.pull_requests[0].head.ref }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha || github.event.workflow_run.pull_requests[0].head.sha }}
      run: bash ${{ github.action_path }}/script.sh
