name: 'Create Infrastructure Summary'
description: 'Creates a GitHub Actions step summary for infrastructure deployments'
inputs:
  terraform-changed:
    description: 'Whether terraform files changed (true/false)'
    required: true
  terraform-result:
    description: 'Result of terraform job'
    required: true
runs:
  using: composite
  steps:
    - name: Create summary
      shell: bash
      run: |
        echo "## ðŸ—ï¸ Infrastructure Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ inputs.terraform-changed }}" != "true" ]; then
          echo "â­ï¸ **Skipped** - No terraform changes in this commit" >> $GITHUB_STEP_SUMMARY
        else
          echo "### Pipeline Status" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Terraform | ${{ inputs.terraform-result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "*Note: Detailed terraform plan results are available in the step summary above*" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "*PR comments with full plan details are also posted on the pull request*" >> $GITHUB_STEP_SUMMARY
          fi
        fi
