name: Run ruff checks
description: Runs ruff linter and formatter checks on Python code

inputs:
  target-path:
    description: Path to check with ruff
    required: false
    default: 'services/'
  config-path:
    description: Path to ruff configuration file
    required: false
    default: 'services/ruff.toml'

runs:
  using: composite
  steps:
    - name: Install ruff
      shell: bash
      run: pip install ruff

    - name: Run ruff linter
      shell: bash
      run: |
        echo "🔍 Running ruff linter..."
        ruff check ${{ inputs.target-path }} --config=${{ inputs.config-path }}

    - name: Run ruff formatter check
      shell: bash
      run: |
        echo "✨ Checking ruff formatting..."
        ruff format --check ${{ inputs.target-path }} --config=${{ inputs.config-path }}
