name: Run ruff checks
description: Runs ruff linter and formatter checks on Python code

inputs:
  target-path:
    description: Path to check with ruff
    required: false
    default: 'services/'

runs:
  using: composite
  steps:
    - name: Install ruff
      shell: bash
      run: pip install ruff

    - name: Run ruff linter
      shell: bash
      working-directory: ${{ inputs.target-path }}
      run: |
        echo "🔍 Running ruff linter in ${{ inputs.target-path }}..."
        # Ruff auto-discovers configuration from pyproject.toml or ruff.toml
        # in the current directory or parent directories
        ruff check .

    - name: Run ruff formatter check
      shell: bash
      working-directory: ${{ inputs.target-path }}
      run: |
        echo "✨ Checking ruff formatting in ${{ inputs.target-path }}..."
        ruff format --check .
