name: Run ruff checks
description: Runs ruff linter and formatter checks on Python code

inputs:
  target-path:
    description: Path to check with ruff
    required: false
    default: 'services/'

runs:
  using: composite
  steps:
    - name: Run ruff checks
      shell: bash
      env:
        TARGET_PATH: ${{ inputs.target-path }}
      run: bash ${{ github.action_path }}/script.sh
