name: 'Create Preview Deployment Summary'
description: 'Creates a GitHub Actions step summary for preview deployments'
inputs:
  pr-number:
    description: 'Pull request number'
    required: true
  preview-url:
    description: 'Preview environment URL'
    required: true
  image-tag:
    description: 'Docker image tag deployed'
    required: true
  commit-sha:
    description: 'Git commit SHA'
    required: true
runs:
  using: composite
  steps:
    - name: Create deployment summary
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        PREVIEW_URL: ${{ inputs.preview-url }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
      run: bash ${{ github.action_path }}/script.sh
