name: Check Preview Concurrency
description: Check if preview deployment is allowed based on concurrent preview limit

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  max-previews:
    description: Maximum number of concurrent previews allowed
    required: false
    default: '10'

outputs:
  can_deploy:
    description: Whether the preview can be deployed
    value: ${{ steps.check.outputs.can_deploy }}

runs:
  using: composite
  steps:
    - name: Count active previews
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        MAX_PREVIEWS: ${{ inputs.max-previews }}
      run: bash ${{ github.action_path }}/script.sh
