# Reusable Kustomize validation action
# Validates Kustomize builds with comprehensive error diagnostics

name: 'Validate Kustomize Build'
description: 'Build and validate Kustomize overlay with detailed error reporting'

inputs:
  overlay-path:
    description: 'Path to kustomize overlay directory (e.g., k8s/overlays/preview)'
    required: true
  overlay-name:
    description: 'Name of the overlay for error messages (e.g., preview, prod)'
    required: true
  dry-run:
    description: 'Perform kubectl server-side dry-run validation'
    required: false
    default: 'false'
  max-cpu:
    description: 'Maximum CPU quota in millicores (optional)'
    required: false
    default: ''
  output-file:
    description: 'Output file path for built manifests'
    required: false
    default: ''

outputs:
  manifest-path:
    description: 'Path to the generated manifest file'
    value: ${{ steps.build.outputs.manifest_path }}
  manifest-size:
    description: 'Size of the generated manifest in bytes'
    value: ${{ steps.build.outputs.manifest_size }}

runs:
  using: 'composite'
  steps:
    - name: Build Kustomize overlay
      id: build
      shell: bash
      env:
        OVERLAY_DIR: ${{ inputs.overlay-path }}
        OVERLAY_NAME: ${{ inputs.overlay-name }}
        OUTPUT_FILE: ${{ inputs.output-file }}
      run: ${{ github.action_path }}/build-overlay.sh

    - name: Validate YAML syntax
      shell: bash
      env:
        MANIFEST: ${{ steps.build.outputs.manifest_path }}
      run: ${{ github.action_path }}/validate-yaml.sh

    - name: Validate CPU quotas
      if: inputs.max-cpu != ''
      shell: bash
      env:
        MANIFEST: ${{ steps.build.outputs.manifest_path }}
        MAX_CPU: ${{ inputs.max-cpu }}
        OVERLAY_NAME: ${{ inputs.overlay-name }}
      run: ${{ github.action_path }}/validate-cpu-quotas.sh

    - name: Server-side dry-run
      if: inputs.dry-run == 'true'
      shell: bash
      env:
        MANIFEST: ${{ steps.build.outputs.manifest_path }}
        OVERLAY_NAME: ${{ inputs.overlay-name }}
      run: ${{ github.action_path }}/validate-dry-run.sh
