# Reusable image tag generator
# Creates consistent image tags based on PR number, commit SHA, or branch

name: 'Generate Image Tag'
description: 'Generate image tag from PR number and commit SHA'

inputs:
  pr-number:
    description: 'Pull request number'
    required: false
    default: ''
  commit-sha:
    description: 'Commit SHA'
    required: false
    default: ''
  branch-name:
    description: 'Branch name'
    required: false
    default: ''
  tag-prefix:
    description: 'Tag prefix (e.g., pr, sha, branch)'
    required: false
    default: 'auto'

outputs:
  image-tag:
    description: 'Generated image tag'
    value: ${{ steps.generate.outputs.image_tag }}
  short-sha:
    description: 'Short commit SHA (7 characters)'
    value: ${{ steps.generate.outputs.short_sha }}
  tag-type:
    description: 'Type of tag generated (pr, sha, branch)'
    value: ${{ steps.generate.outputs.tag_type }}

runs:
  using: 'composite'
  steps:
    - name: Generate image tag
      id: generate
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        BRANCH_NAME: ${{ inputs.branch-name }}
        TAG_PREFIX: ${{ inputs.tag-prefix }}
      run: ${{ github.action_path }}/generate-image-tag.sh
