# Reusable Azure ACR login action
# Authenticates to Azure via OIDC and logs into Azure Container Registry

name: 'Azure ACR Login'
description: 'Login to Azure via OIDC and authenticate to ACR'

inputs:
  azure-client-id:
    description: 'Azure Client ID'
    required: true
  azure-tenant-id:
    description: 'Azure Tenant ID'
    required: true
  azure-subscription-id:
    description: 'Azure Subscription ID'
    required: true
  acr-name:
    description: 'Azure Container Registry name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        auth-type: OIDC
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Login to ACR
      shell: bash
      run: az acr login --name ${{ inputs.acr-name }}
