name: Record Test Duration
description: Records test execution start and finish times for reporting

inputs:
  start-time:
    description: Test start time (epoch seconds). If not provided, records current time as start.
    required: false
    default: ''
  test-name:
    description: Name of the test suite for logging
    required: false
    default: 'Tests'

outputs:
  started_at:
    description: Test start time (epoch seconds)
    value: ${{ steps.record.outputs.started_at }}
  test_duration:
    description: Test duration in seconds (only available after finish)
    value: ${{ steps.record.outputs.test_duration }}

runs:
  using: composite
  steps:
    - name: Record test timing
      id: record
      shell: bash
      env:
        START_TIME: ${{ inputs.start-time }}
        TEST_NAME: ${{ inputs.test-name }}
      run: bash ${{ github.action_path }}/script.sh
