name: Wait for CI Workflow
description: |
  Waits for CI workflow to complete successfully and retrieves the image tag artifact.
  This ensures preview deployments only proceed with successfully built images.

  ARTIFACT RETRIEVAL: Downloads 'image-tag' artifact from CI run containing the
  Docker image tag. If no artifact exists (CI didn't build images), returns empty string.
  Preview workflow validates this and skips deployment if no images are available.

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  commit-sha:
    description: Commit SHA to check
    required: true
  timeout-seconds:
    description: Maximum time to wait in seconds
    required: false
    default: '1800'
  interval-seconds:
    description: Interval between checks in seconds
    required: false
    default: '30'
  workflow-file:
    description: Workflow file name to monitor
    required: false
    default: 'ci.yml'

outputs:
  image_tag:
    description: "Image tag fetched from CI artifacts (if available)"
    value: ${{ steps.wait.outputs.image_tag }}
  ci_run_id:
    description: "CI workflow run id for artifact downloads"
    value: ${{ steps.wait.outputs.ci_run_id }}

runs:
  using: composite
  steps:
    - name: Wait for CI workflow (exit early on failure and fetch image tag)
      id: wait
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        TIMEOUT_SECONDS: ${{ inputs.timeout-seconds }}
        INTERVAL_SECONDS: ${{ inputs.interval-seconds }}
        WORKFLOW_FILE: ${{ inputs.workflow-file }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: bash ${{ github.action_path }}/script.sh
