name: Post Preview Comment
description: Post or update comprehensive preview environment comment on PR

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  pr-number:
    description: Pull request number
    required: true
  preview-url:
    description: Preview environment URL
    required: true
  image-tag:
    description: Docker image tag deployed
    required: true
  commit-sha:
    description: Commit SHA deployed
    required: true
  frontend-url:
    description: Frontend preview URL
    required: false
    default: ''
  run-id:
    description: GitHub Actions run ID for linking
    required: false
    default: ''
  repository:
    description: GitHub repository (owner/repo)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Post/update PR comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const previewUrl = '${{ inputs.preview-url }}';
          const frontendUrl = '${{ inputs.frontend-url }}';
          const imageTag = '${{ inputs.image-tag }}';
          const commitSha = '${{ inputs.commit-sha }}';
          const runId = '${{ inputs.run-id }}' || context.runId;
          const repo = '${{ inputs.repository }}' || `${context.repo.owner}/${context.repo.repo}`;

          const body = `## 🚀 Preview Environment Deployed\n\n` +
            `### 🌐 Environment URLs\n\n` +
            `| Environment | URL |\n` +
            `|-------------|-----|\n` +
            `| **🔌 Backend API** | [${previewUrl}](${previewUrl}) |\n` +
            (frontendUrl ? `| **🖥️ Frontend App** | [${frontendUrl}](${frontendUrl}) |\n` : '') +
            `| **❤️ Health Check** | [${previewUrl}/health/live](${previewUrl}/health/live) |\n` +
            `| **📖 API Docs** | [${previewUrl}/docs](${previewUrl}/docs) |\n\n` +
            `### 📦 Deployment Details\n\n` +
            `| Property | Value |\n` +
            `|----------|-------|\n` +
            `| **Image Tag** | \`${imageTag}\` |\n` +
            `| **Commit** | [\`${commitSha.substring(0, 7)}\`](https://github.com/${repo}/commit/${commitSha}) |\n` +
            `| **Workflow Run** | [View Logs](https://github.com/${repo}/actions/runs/${runId}) |\n\n` +
            `### 🔗 Quick Actions\n\n` +
            `<details>\n` +
            `<summary>🧪 Test Commands</summary>\n\n` +
            `\`\`\`bash\n` +
            `# Test API health\n` +
            `curl -s ${previewUrl}/health/live | jq\n\n` +
            `# Test API readiness\n` +
            `curl -s ${previewUrl}/health/ready | jq\n\n` +
            `# List videos\n` +
            `curl -s ${previewUrl}/api/videos | jq\n` +
            `\`\`\`\n` +
            `</details>\n\n` +
            `<details>\n` +
            `<summary>☸️ Kubernetes Commands</summary>\n\n` +
            `\`\`\`bash\n` +
            `# View preview pods\n` +
            `kubectl get pods -n preview-pr-${{ inputs.pr-number }}\n\n` +
            `# View API logs\n` +
            `kubectl logs -n preview-pr-${{ inputs.pr-number }} -l app=api --tail=100\n\n` +
            `# View deployment status\n` +
            `kubectl get deployments -n preview-pr-${{ inputs.pr-number }}\n` +
            `\`\`\`\n` +
            `</details>\n\n` +
            `---\n` +
            `_This preview will be automatically cleaned up when the PR is closed or merged._`;

          // Find existing preview comment to update
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ inputs.pr-number }},
          });

          const previewComment = comments.find(c =>
            c.user.type === 'Bot' &&
            c.body.includes('Preview Environment Deployed')
          );

          if (previewComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: previewComment.id,
              body: body
            });
            console.log('Updated existing preview comment');
          } else {
            await github.rest.issues.createComment({
              issue_number: ${{ inputs.pr-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
            console.log('Created new preview comment');
          }

    - name: Create deployment summary
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        PREVIEW_URL: ${{ inputs.preview-url }}
        FRONTEND_URL: ${{ inputs.frontend-url }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
      run: ${{ github.action_path }}/post-preview-comment.sh
