#!/bin/bash
# Unified commit script for kustomization changes
# Handles preview, prod, and generic commit operations

set -euo pipefail

# Determine what to commit based on operation
case "$OPERATION" in
  update-preview)
    # Preview overlays are stored in PR-specific directories on the preview-overlays branch
    # This prevents commits to PR branches which would invalidate CI status
    FILE_TO_COMMIT="${OVERLAY_PATH:-k8s/overlays/preview-pr-${PR_NUMBER}}/kustomization.yaml"
    BRANCH="preview-overlays"
    MESSAGE="ci(preview): update overlay for PR #${PR_NUMBER} with image ${IMAGE_TAG}

- Image: ${IMAGE_TAG}
- Commit: ${COMMIT_SHA:0:7}
- PR Branch: ${PR_BRANCH}
- Auto-generated by GitHub Actions

[skip ci]"
    ;;

  update-prod)
    FILE_TO_COMMIT="${KUSTOMIZATION_PATH}/kustomization.yaml"
    BRANCH="${GIT_BRANCH}"
    MESSAGE="ci(prod): update kustomization with image ${IMAGE_TAG}

- Image: ${IMAGE_TAG}
- Auto-generated by GitHub Actions

[skip ci]"
    ;;

  commit-only)
    FILE_TO_COMMIT="${FILE_PATH}"
    BRANCH="${GIT_BRANCH}"
    MESSAGE="${COMMIT_MESSAGE}"
    ;;

  *)
    echo "::error::Invalid operation: $OPERATION"
    exit 1
    ;;
esac

echo "📝 Committing changes..."
echo "  File: $FILE_TO_COMMIT"
echo "  Branch: $BRANCH"

# Configure git
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

# For preview overlays, we need to work with the dedicated preview-overlays branch
if [ "$OPERATION" == "update-preview" ]; then
  echo "🔄 Setting up preview-overlays branch..."

  # Save the current branch/ref so we can return to it later
  ORIGINAL_REF=$(git rev-parse HEAD)
  ORIGINAL_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "detached")

  # The overlay directory was generated in the current branch but needs to be committed to preview-overlays
  # Move it to a temp location before switching branches to avoid git conflicts
  OVERLAY_DIR="$(dirname "$FILE_TO_COMMIT")"
  TEMP_OVERLAY_DIR="/tmp/preview-overlay-dir-${PR_NUMBER}"
  TEMP_BASE_DIR="/tmp/preview-base-${PR_NUMBER}"

  if [ -d "$OVERLAY_DIR" ]; then
    echo "📦 Saving generated overlay directory to temp location..."
    cp -r "$OVERLAY_DIR" "$TEMP_OVERLAY_DIR"
    # Also copy the base-preview directory - required for kustomization to work
    # The overlay references ../../base-preview which must exist on preview-overlays branch
    if [ -d "k8s/base-preview" ]; then
      echo "📦 Saving base-preview directory to temp location..."
      cp -r "k8s/base-preview" "$TEMP_BASE_DIR"
    else
      echo "::error::base-preview directory not found at k8s/base-preview"
      exit 1
    fi
    # Remove the directory to avoid checkout conflicts
    rm -rf "$OVERLAY_DIR"
  else
    echo "::error::Preview overlay directory not found at $OVERLAY_DIR. Was update-preview.sh run first?"
    exit 1
  fi

  # Fetch the preview-overlays branch if it exists
  git fetch origin "$BRANCH" 2>/dev/null || true

  # Check if remote branch exists
  if git rev-parse "origin/$BRANCH" > /dev/null 2>&1; then
    # Branch exists, check it out
    git checkout -B "$BRANCH" "origin/$BRANCH"
  else
    # Branch doesn't exist, create it as orphan from main
    echo "ℹ️  Creating new preview-overlays branch..."
    git checkout --orphan "$BRANCH"
    # Remove all files from staging (orphan branch)
    git rm -rf . 2>/dev/null || true
  fi

  # Ensure the k8s/overlays directory structure exists
  mkdir -p "$(dirname "$OVERLAY_DIR")"

  # Restore the entire overlay directory from temp location
  echo "📥 Restoring overlay directory to preview-overlays branch..."
  cp -r "$TEMP_OVERLAY_DIR" "$OVERLAY_DIR"
  rm -rf "$TEMP_OVERLAY_DIR"

  # Restore the base-preview directory
  # This is needed because kustomization.yaml references ../../base-preview
  echo "📥 Restoring base-preview directory to preview-overlays branch..."
  mkdir -p "k8s"
  cp -r "$TEMP_BASE_DIR" "k8s/base-preview"
  rm -rf "$TEMP_BASE_DIR"
fi

# Check if file exists (should exist by now)
if [ ! -f "$FILE_TO_COMMIT" ]; then
  echo "::error::File not found: $FILE_TO_COMMIT"
  exit 1
fi

# Check if there are changes (for tracked files) or if file is new
if git diff --quiet "$FILE_TO_COMMIT" 2>/dev/null && git ls-files --error-unmatch "$FILE_TO_COMMIT" > /dev/null 2>&1; then
  echo "ℹ️  No changes to commit"
  echo "committed=false" >> "$GITHUB_OUTPUT"

  # For preview operations, switch back to the original branch before exiting
  # This ensures subsequent workflow steps can find the .github/actions/ directory
  if [ "$OPERATION" == "update-preview" ]; then
    echo "🔙 Switching back to original branch..."
    if [ "$ORIGINAL_BRANCH" != "detached" ]; then
      git checkout "$ORIGINAL_BRANCH" 2>/dev/null || git checkout "$ORIGINAL_REF"
    else
      git checkout "$ORIGINAL_REF"
    fi
  fi
  exit 0
fi

# Add and commit
git add "$FILE_TO_COMMIT"
# For preview overlays, also add the entire overlay directory and base-preview directory
if [ "$OPERATION" == "update-preview" ]; then
  OVERLAY_DIR="$(dirname "$FILE_TO_COMMIT")"
  git add "$OVERLAY_DIR"
  git add "k8s/base-preview"
fi
git commit -m "$MESSAGE"

# For non-preview operations, handle the original branch logic
if [ "$OPERATION" != "update-preview" ]; then
  # Handle detached HEAD - checkout branch if needed
  if ! git symbolic-ref HEAD > /dev/null 2>&1; then
    echo "ℹ️  Detached HEAD detected, checking out branch..."
    git checkout -B "$BRANCH"
  fi

  # Fetch latest changes and rebase our commit on top
  echo "📥 Fetching latest changes..."
  git fetch origin "$BRANCH"

  # Check if remote branch exists and has diverged
  if git rev-parse "origin/$BRANCH" > /dev/null 2>&1; then
    echo "🔄 Rebasing on latest changes..."
    if ! git rebase "origin/$BRANCH"; then
      echo "⚠️  Rebase conflict detected - auto-resolving with our version..."
      # Use our version for the kustomization file (it's auto-generated, ours is correct)
      git checkout --ours "$FILE_TO_COMMIT"
      git add "$FILE_TO_COMMIT"
      git rebase --continue

      # If rebase still fails, abort and try force push with lease
      if [ $? -ne 0 ]; then
        echo "⚠️  Rebase failed, using force-with-lease push instead..."
        git rebase --abort
        git push --force-with-lease origin "HEAD:$BRANCH"
        echo "✅ Changes force-pushed with lease"
        echo "committed=true" >> "$GITHUB_OUTPUT"
        exit 0
      fi
    fi
  fi
fi

echo "🚀 Pushing to $BRANCH..."
git push origin "HEAD:$BRANCH"

# For preview operations, switch back to the original branch
# This ensures subsequent workflow steps can find the .github/actions/ directory
if [ "$OPERATION" == "update-preview" ]; then
  echo "🔙 Switching back to original branch..."
  if [ "$ORIGINAL_BRANCH" != "detached" ]; then
    git checkout "$ORIGINAL_BRANCH"
  else
    git checkout "$ORIGINAL_REF"
  fi
fi

echo "✅ Changes committed and pushed"
echo "committed=true" >> "$GITHUB_OUTPUT"
