name: 'Validate Kubernetes YAML'
description: 'Validates YAML syntax for all Kubernetes manifest files'

inputs:
  directory:
    description: 'Directory containing Kubernetes manifests'
    required: false
    default: 'k8s'

runs:
  using: composite
  steps:
    - name: Validate YAML syntax
      shell: bash
      working-directory: ${{ inputs.directory != '.' && inputs.directory || github.workspace }}
      run: python3 ${{ github.action_path }}/validate-k8s-yaml.py
      env:
        SEARCH_DIR: ${{ inputs.directory }}
