name: Detect Pipeline Changes
description: Detects which parts of the codebase have changed to optimize pipeline execution

outputs:
  changed_areas:
    description: Space-separated list of changed areas (e.g., "apps/web services/api k8s")
    value: ${{ steps.detect.outputs.changed_areas }}
  has_code_changes:
    description: Whether code changes exist (excludes docs-only changes)
    value: ${{ steps.detect.outputs.has_code_changes }}

runs:
  using: composite
  steps:
    - name: Detect changes
      id: detect
      shell: pwsh
      run: .\scripts\ci\detect-changes.ps1 -OutputFormat github-actions
