# =============================================================================
# Detect Pipeline Changes - Smart Change Detection
# =============================================================================
# DESIGN DECISION: Dumb detection, smart consumption
#
# This action outputs RAW change data, not execution decisions:
#   - changed_areas: space-separated list of changed paths
#   - has_code_changes: boolean flag (excludes docs)
#   - needs_image_build: whether code changes require new images
#   - needs_deployment: whether any deployment is needed
#
# Jobs use contains() to check if their area changed:
#   if: contains(needs.detect-changes.outputs.changed_areas, 'apps/web')
#
# WHY THIS APPROACH?
# ✅ Maintainable: Add new jobs without touching this action
# ✅ Flexible: Jobs can combine multiple area checks with OR/AND
# ✅ Transparent: Each job's condition is self-documenting
# ✅ Testable: Easy to verify job conditions in workflows
#
# ❌ AVOID: Adding stage_test_* or stage_build_* outputs here
#    That couples detection logic to pipeline structure (brittle!)
# =============================================================================
name: Detect Pipeline Changes
description: Detects which parts of the codebase have changed to optimize pipeline execution

inputs:
  base-sha:
    description: 'Base commit SHA to compare against (defaults to auto-detect based on event type)'
    required: false
    default: ''
  head-sha:
    description: 'Head commit SHA to compare (defaults to HEAD)'
    required: false
    default: 'HEAD'

outputs:
  changed_areas:
    description: Space-separated list of changed areas (e.g., "apps/web services/api k8s")
    value: ${{ steps.detect.outputs.changed_areas }}
  has_code_changes:
    description: Whether code changes exist (excludes docs-only changes)
    value: ${{ steps.detect.outputs.has_code_changes }}
  needs_image_build:
    description: Whether changes require building new Docker images
    value: ${{ steps.detect.outputs.needs_image_build }}
  needs_deployment:
    description: Whether changes require deployment (includes k8s-only changes)
    value: ${{ steps.detect.outputs.needs_deployment }}

runs:
  using: composite
  steps:
    - name: Detect changes
      id: detect
      shell: pwsh
      env:
        BASE_SHA_INPUT: ${{ inputs.base-sha }}
        HEAD_SHA_INPUT: ${{ inputs.head-sha }}
      run: |
        & ${{ github.action_path }}/detect-changes.ps1 -OutputFormat 'github-actions'
