name: Validate Terraform Configuration
description: Initializes and validates Terraform configuration

inputs:
  working-directory:
    description: Directory containing Terraform configuration
    required: true
  backend-config:
    description: Whether to initialize with backend configuration
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Terraform validation
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        BACKEND_CONFIG: ${{ inputs.backend-config }}
      run: bash ${{ github.action_path }}/script.sh
