name: Setup Azure and AKS Context
description: Login to Azure via OIDC and set AKS cluster context

inputs:
  azure-client-id:
    description: Azure client ID
    required: true
  azure-tenant-id:
    description: Azure tenant ID
    required: true
  azure-subscription-id:
    description: Azure subscription ID
    required: true
  resource-group:
    description: Azure resource group (uses default if not provided)
    required: false
    default: 'rg-ytsumm-prd'
  cluster-name:
    description: AKS cluster name (uses default if not provided)
    required: false
    default: 'aks-ytsumm-prd'

runs:
  using: composite
  steps:
    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ inputs.resource-group }}
        cluster-name: ${{ inputs.cluster-name }}
