name: 'Setup Terraform with Azure'
description: 'Sets up Terraform, verifies Azure credentials, and authenticates via OIDC in a single reusable action'
inputs:
  terraform-version:
    description: 'Terraform version to install'
    required: false
    default: '1.5.7'
  azure-client-id:
    description: 'Azure client ID for OIDC authentication'
    required: true
  azure-tenant-id:
    description: 'Azure tenant ID for OIDC authentication'
    required: true
  azure-subscription-id:
    description: 'Azure subscription ID for OIDC authentication'
    required: true
runs:
  using: composite
  steps:
    - name: Verify Azure credentials are configured
      uses: ./.github/actions/verify-azure-credentials
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
