name: 'Create CI Summary'
description: 'Creates a rich GitHub step summary with test results, timings, and change detection'

inputs:
  changed-areas:
    description: 'Space-separated list of changed areas'
    required: true
  commit-sha:
    description: 'Git commit SHA'
    required: true
  pr-number:
    description: 'Pull request number (empty for push to main)'
    required: false
    default: ''
  # Lint results
  lint-python-result:
    description: 'Result of lint-python job'
    required: false
    default: 'skipped'
  frontend-quality-result:
    description: 'Result of frontend-quality job'
    required: false
    default: 'skipped'
  # Security results
  scan-python-security-result:
    description: 'Result of scan-python-security job'
    required: false
    default: 'skipped'
  secret-scanning-result:
    description: 'Result of secret-scanning job'
    required: false
    default: 'skipped'
  # Test results with metadata
  test-shared-result:
    description: 'Result of test-shared job'
    required: false
    default: 'skipped'
  test-shared-duration:
    description: 'Duration of test-shared job'
    required: false
    default: ''
  test-api-result:
    description: 'Result of test-api job'
    required: false
    default: 'skipped'
  test-api-duration:
    description: 'Duration of test-api job'
    required: false
    default: ''
  test-workers-result:
    description: 'Result of test-workers job'
    required: false
    default: 'skipped'
  test-workers-duration:
    description: 'Duration of test-workers job'
    required: false
    default: ''
  # Validation results
  kubernetes-validate-result:
    description: 'Result of kubernetes-validate job'
    required: false
    default: 'skipped'
  validate-kustomize-result:
    description: 'Result of validate-kustomize job'
    required: false
    default: 'skipped'
  validate-terraform-result:
    description: 'Result of validate-terraform job'
    required: false
    default: 'skipped'
  # Build results
  build-images-result:
    description: 'Result of build-images job'
    required: false
    default: 'skipped'
  image-tag:
    description: 'Docker image tag generated'
    required: false
    default: ''
  # Repository info
  repository:
    description: 'GitHub repository (owner/repo)'
    required: true
  run-id:
    description: 'GitHub Actions run ID'
    required: true

runs:
  using: composite
  steps:
    - name: Generate CI Summary
      shell: bash
      env:
        CHANGED_AREAS: ${{ inputs.changed-areas }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        PR_NUMBER: ${{ inputs.pr-number }}
        LINT_PYTHON_RESULT: ${{ inputs.lint-python-result }}
        FRONTEND_QUALITY_RESULT: ${{ inputs.frontend-quality-result }}
        SCAN_PYTHON_SECURITY_RESULT: ${{ inputs.scan-python-security-result }}
        SECRET_SCANNING_RESULT: ${{ inputs.secret-scanning-result }}
        TEST_SHARED_RESULT: ${{ inputs.test-shared-result }}
        TEST_SHARED_DURATION: ${{ inputs.test-shared-duration }}
        TEST_API_RESULT: ${{ inputs.test-api-result }}
        TEST_API_DURATION: ${{ inputs.test-api-duration }}
        TEST_WORKERS_RESULT: ${{ inputs.test-workers-result }}
        TEST_WORKERS_DURATION: ${{ inputs.test-workers-duration }}
        KUBERNETES_VALIDATE_RESULT: ${{ inputs.kubernetes-validate-result }}
        VALIDATE_KUSTOMIZE_RESULT: ${{ inputs.validate-kustomize-result }}
        VALIDATE_TERRAFORM_RESULT: ${{ inputs.validate-terraform-result }}
        BUILD_IMAGES_RESULT: ${{ inputs.build-images-result }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        REPOSITORY: ${{ inputs.repository }}
        RUN_ID: ${{ inputs.run-id }}
      run: ${{ github.action_path }}/generate-summary.sh
