name: 'Cleanup ACR Images'
description: 'Deletes preview environment images from Azure Container Registry'
inputs:
  acr-name:
    description: 'Azure Container Registry name'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  repositories:
    description: 'Comma-separated list of repositories to clean (e.g., "yt-summarizer-api,yt-summarizer-workers")'
    required: false
    default: 'yt-summarizer-api,yt-summarizer-workers'
runs:
  using: composite
  steps:
    - name: Delete PR images from ACR
      shell: bash
      env:
        ACR_NAME: ${{ inputs.acr-name }}
        PR_NUMBER: ${{ inputs.pr-number }}
        REPOSITORIES: ${{ inputs.repositories }}
      run: ${{ github.action_path }}/cleanup-acr-images.sh
