name: Detect PR Code Changes
description: |
  Detects if a PR contains changes that would trigger image building in CI.
  Uses git diff to reliably get ALL changed files between base and head commits.
  Only returns true for changes in: services/api, services/workers, services/shared, apps/web, docker files.
  This ensures preview deployments only run when images are actually available.

  BETTER APPROACH: Uses git diff instead of GitHub API for reliability.
  No longer limited by API pagination or commit history issues.

inputs:
  base-sha:
    description: Base commit SHA to compare against (defaults to origin/main)
    required: false
    default: 'origin/main'
  head-sha:
    description: Head commit SHA to compare (defaults to HEAD)
    required: false
    default: 'HEAD'
  force-preview-labels:
    description: Comma-separated list of labels that force preview deployment
    required: false
    default: 'preview,force-preview'
  pr-number:
    description: PR number to check for force labels (optional)
    required: false
  force-deploy:
    description: Force deployment regardless of changes
    required: false
    default: 'false'

outputs:
  has_code_changes:
    description: Whether the PR contains code changes
    value: ${{ steps.detect.outputs.has_code_changes }}

runs:
  using: composite
  steps:
    - name: Detect code changes
      id: detect
      shell: bash
      run: |
        # Fetch all changed files using git diff (more reliable than GitHub API)
        # This ensures we get ALL files changed in the PR, not just recent commits
        BASE_SHA="${{ inputs.base-sha }}"
        HEAD_SHA="${{ inputs.head-sha }}"
        FORCE_LABELS="${{ inputs.force-preview-labels }}"
        PR_NUMBER="${{ inputs.pr-number }}"
        FORCE_DEPLOY="${{ inputs.force-deploy }}"
        
        echo "Comparing: $BASE_SHA...$HEAD_SHA"
        
        # Check for force preview labels if PR number provided
        FORCE_DEPLOY=false
        if [ -n "$PR_NUMBER" ] && [ -n "$FORCE_LABELS" ]; then
          echo "Checking for force preview labels on PR #$PR_NUMBER..."
          
          # Get PR labels using GitHub API
          if [ -n "$GITHUB_TOKEN" ]; then
            API_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER"
            LABELS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$API_URL" | jq -r '.labels[].name' 2>/dev/null || echo "")
            
            if [ -n "$LABELS" ]; then
              echo "PR labels: $LABELS"
              
              # Check if any force label is present
              IFS=',' read -ra LABEL_ARRAY <<< "$FORCE_LABELS"
              for label in "${LABEL_ARRAY[@]}"; do
                label=$(echo "$label" | xargs)  # trim whitespace
                if echo "$LABELS" | grep -q "^$label$"; then
                  echo "✅ Force preview label '$label' found - forcing deployment"
                  FORCE_DEPLOY=true
                  break
                fi
              done
            else
              echo "Could not fetch PR labels"
            fi
          else
            echo "No GITHUB_TOKEN available for API calls"
          fi
        fi
        
        # For manual workflow_dispatch triggers, always force deploy (no PR context needed)
        if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] || [ "$FORCE_DEPLOY" = "true" ]; then
          echo "🚀 Force deployment requested - proceeding with deployment"
          FORCE_DEPLOY=true
        fi
        
        if [ "$FORCE_DEPLOY" = "true" ]; then
          echo "has_code_changes=true" >> $GITHUB_OUTPUT
          echo "🚀 Force deploying due to label"
          exit 0
        fi
        
        # Get all changed files using git diff
        FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" 2>/dev/null || echo "")
        
        if [ -z "$FILES" ]; then
          echo "⚠️ Could not fetch changed files using git diff - assuming no code changes"
          echo "has_code_changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Files changed in this comparison:"
        echo "$FILES"

        # Check if any file would trigger image building in CI
        # CRITICAL FIX: Only return true for changes that actually build images in CI workflow
        # This prevents preview deployments when no images are available
        #
        # CI BUILD TRIGGERS (build-images-meta job):
        # - services/api/** (API service)
        # - services/workers/** (background workers)
        # - services/shared/** (shared libraries)
        # - apps/web/** (frontend application)
        # - **/Dockerfile* (Docker files)
        # - docker-compose*.yml (compose files)
        # - .dockerignore (docker config)
        #
        # ROOT CAUSE: Previously checked for ANY non-docs change, causing preview to run
        # even when CI skipped image building (e.g., workflow-only changes)
        HAS_CODE=false
        while IFS= read -r file; do
          if [[ -n "$file" ]]; then
            # Skip docs, specs, and markdown files
            if [[ "$file" == docs/* ]] || [[ "$file" == specs/* ]] || [[ "$file" == *.md ]]; then
              echo "  [skip] $file (docs/specs/markdown)"
            # Check if file is in areas that trigger image building
            elif [[ "$file" == services/api/** ]] || [[ "$file" == services/workers/** ]] || [[ "$file" == services/shared/** ]] || [[ "$file" == apps/web/** ]] || [[ "$file" == **/Dockerfile* ]] || [[ "$file" == docker-compose*.yml ]] || [[ "$file" == .dockerignore ]]; then
              echo "  [BUILD] $file (triggers image build)"
              HAS_CODE=true
            else
              echo "  [skip] $file (does not trigger image build)"
            fi
          fi
        done <<< "$FILES"

        echo "has_code_changes=$HAS_CODE" >> $GITHUB_OUTPUT

        if [ "$HAS_CODE" = "true" ]; then
          echo "✅ Comparison contains changes that trigger image building"
        else
          echo "📝 Comparison contains only documentation changes or changes that don't require image building"
        fi
