name: Detect PR Code Changes
description: |
  Detects if a PR contains changes that would trigger image building in CI.
  Uses git diff to reliably get ALL changed files between base and head commits.
  Only returns true for changes in: services/api, services/workers, services/shared, apps/web, docker files.
  This ensures preview deployments only run when images are actually available.

  BETTER APPROACH: Uses git diff instead of GitHub API for reliability.
  No longer limited by API pagination or commit history issues.

inputs:
  base-sha:
    description: Base commit SHA to compare against (defaults to origin/main)
    required: false
    default: 'origin/main'
  head-sha:
    description: Head commit SHA to compare (defaults to HEAD)
    required: false
    default: 'HEAD'
  force-preview-labels:
    description: Comma-separated list of labels that force preview deployment
    required: false
    default: 'preview,force-preview'
  pr-number:
    description: PR number to check for force labels (optional)
    required: false
  force-deploy:
    description: Force deployment regardless of changes
    required: false
    default: 'false'

outputs:
  needs_image_build:
    description: Whether the PR contains changes that require building new images
    value: ${{ steps.detect.outputs.needs_image_build }}
  needs_deployment:
    description: Whether the PR contains changes that require deployment
    value: ${{ steps.detect.outputs.needs_deployment }}

runs:
  using: composite
  steps:
    - name: Detect code changes
      id: detect
      shell: bash
      env:
        BASE_SHA: ${{ inputs.base-sha }}
        HEAD_SHA: ${{ inputs.head-sha }}
        FORCE_LABELS: ${{ inputs.force-preview-labels }}
        PR_NUMBER: ${{ inputs.pr-number }}
        FORCE_DEPLOY: ${{ inputs.force-deploy }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: ${{ github.action_path }}/detect-changes.sh
