name: 'Health Check Preview Environment'
description: 'Performs health checks on preview environment API (internal cluster + external ingress)'
inputs:
  namespace:
    description: 'Kubernetes namespace for the preview environment'
    required: true
  external-url:
    description: 'External URL to check (e.g., https://api.preview-pr-4.example.com)'
    required: true
  max-attempts:
    description: 'Maximum number of health check attempts'
    required: false
    default: '10'
  interval-seconds:
    description: 'Seconds to wait between attempts'
    required: false
    default: '10'

outputs:
  external-healthy:
    description: 'Whether external health check passed'
    value: ${{ steps.external-check.outputs.healthy }}
  internal-healthy:
    description: 'Whether internal health check passed'
    value: ${{ steps.internal-check.outputs.healthy }}
  external-attempts:
    description: 'Number of attempts made for external health check'
    value: ${{ steps.external-check.outputs.attempts }}

runs:
  using: 'composite'
  steps:
    - name: Check internal cluster health
      id: internal-check
      shell: bash
      env:
        NAMESPACE: ${{ inputs.namespace }}
        MAX_ATTEMPTS: ${{ inputs.max-attempts }}
        INTERVAL: ${{ inputs.interval-seconds }}
      run: ${{ github.action_path }}/check-internal-health.sh

    - name: Check DNS resolution
      shell: bash
      env:
        EXTERNAL_URL: ${{ inputs.external-url }}
        NAMESPACE: ${{ inputs.namespace }}
      run: ${{ github.action_path }}/check-dns-resolution.sh

    - name: Check Gateway API HTTPRoute configuration
      shell: bash
      env:
        NAMESPACE: ${{ inputs.namespace }}
      run: ${{ github.action_path }}/check-httproute-config.sh

    - name: Check service and endpoints
      shell: bash
      env:
        NAMESPACE: ${{ inputs.namespace }}
      run: ${{ github.action_path }}/check-service-endpoints.sh

    - name: Check gateway certificate readiness
      shell: bash
      run: ${{ github.action_path }}/check-gateway-cert.sh

    - name: Wait for DNS propagation
      shell: bash
      run: |
        echo "::notice::Waiting 30 seconds for DNS propagation..."
        sleep 30

    - name: Check external ingress health
      id: external-check
      uses: ./.github/actions/health-check
      with:
        url: ${{ inputs.external-url }}/health/live
        max-attempts: ${{ inputs.max-attempts }}
        interval-seconds: ${{ inputs.interval-seconds }}
        timeout-seconds: '5'
        expected-status: '200'
        service-name: 'Preview API (External)'

    - name: Run diagnostics on external health failure
      if: failure() && steps.external-check.outcome == 'failure'
      shell: bash
      env:
        EXTERNAL_URL: ${{ inputs.external-url }}
        NAMESPACE: ${{ inputs.namespace }}
      run: ${{ github.action_path }}/check-external-diagnostics.sh
