name: Publish Image Tag
description: Write the provided image tag to a file and upload it as an artifact

inputs:
  image-tag:
    description: Image tag to publish
    required: true

runs:
  using: composite
  steps:
    - name: Write image tag to file
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: bash ${{ github.action_path }}/script.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: image-tag.txt
