name: Publish Image Tag
description: Write the provided image tag to a file and upload it as an artifact

inputs:
  image-tag:
    description: Image tag to publish
    required: true

runs:
  using: composite
  steps:
    - name: Write image tag to file
      shell: bash
      run: |
        echo "${{ inputs.image-tag }}" > image-tag.txt
        echo "Wrote image tag to image-tag.txt"
        cat image-tag.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: image-tag.txt
