#!/bin/bash
set -euo pipefail

# Generate preview environment kustomization.yaml from template using envsubst
# This script replaces the Python implementation with simple shell scripting

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --template)
      TEMPLATE_FILE="$2"
      shift 2
      ;;
    --output)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --pr-number)
      export PR_NUMBER="$2"
      shift 2
      ;;
    --image-tag)
      export IMAGE_TAG="$2"
      shift 2
      ;;
    --acr-server)
      export ACR_SERVER="$2"
      shift 2
      ;;
    --preview-host)
      export PREVIEW_HOST="$2"
      shift 2
      ;;
    --tls-secret)
      export TLS_SECRET="$2"
      shift 2
      ;;
    --commit-sha)
      export COMMIT_SHA="$2"
      shift 2
      ;;
    --swa-url)
      export SWA_URL="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

# Validate required arguments
: "${TEMPLATE_FILE:?Missing --template argument}"
: "${OUTPUT_FILE:?Missing --output argument}"
: "${PR_NUMBER:?Missing --pr-number argument}"
: "${IMAGE_TAG:?Missing --image-tag argument}"
: "${ACR_SERVER:?Missing --acr-server argument}"
: "${PREVIEW_HOST:?Missing --preview-host argument}"
: "${TLS_SECRET:?Missing --tls-secret argument}"
: "${COMMIT_SHA:?Missing --commit-sha argument}"

# Auto-generate SWA URL if not provided (matches Python logic)
if [ -z "${SWA_URL:-}" ]; then
  export SWA_URL="https://red-grass-06d413100-${PR_NUMBER}.eastasia.6.azurestaticapps.net"
fi

# Generate metadata header
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
HEADER="# Generated by generate_preview_kustomization.sh on ${TIMESTAMP}
# PR: ${PR_NUMBER}
# Image: ${ACR_SERVER}/api:${IMAGE_TAG}
# Preview Host: ${PREVIEW_HOST}
# Commit: ${COMMIT_SHA}

"

# Substitute template variables and write output
echo "$HEADER" > "$OUTPUT_FILE"
envsubst < "$TEMPLATE_FILE" >> "$OUTPUT_FILE"

echo "Generated kustomization.yaml at $OUTPUT_FILE"
