#!/bin/bash
set -euo pipefail

# Generate production kustomization.yaml from template using envsubst
# This script replaces the Python implementation with simple shell scripting

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --image-tag)
      export IMAGE_TAG="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

# Validate required argument
: "${IMAGE_TAG:?Missing --image-tag argument}"

# Define paths
TEMPLATE_FILE="scripts/ci/templates/prod-kustomization-template.yaml"
OUTPUT_FILE="k8s/overlays/prod/kustomization.yaml"

# Generate metadata header
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
HEADER="# Generated by update_prod_kustomization.sh on ${TIMESTAMP}
# Image Tag: ${IMAGE_TAG}

"

# Substitute template variables and write output
echo "$HEADER" > "$OUTPUT_FILE"
envsubst < "$TEMPLATE_FILE" >> "$OUTPUT_FILE"

echo "Updated production kustomization.yaml with image tag: $IMAGE_TAG"
