name: Collect Deployment Diagnostics
description: Collects Argo CD diagnostics on deployment failure and uploads as artifact
inputs:
  app-name:
    description: Argo CD application name or namespace to diagnose
    required: true
  artifact-name:
    description: Artifact name for upload
    required: true
  diagnostics-path:
    description: Path to store diagnostics
    required: false
    default: './diagnostics'
  retention-days:
    description: Number of days to retain the artifact
    required: false
    default: '7'

runs:
  using: composite
  steps:
    - name: Collect deployment diagnostics
      if: failure()
      shell: bash
      run: ./scripts/diagnose-argocd-deployment.sh ${{ inputs.app-name }} ${{ inputs.diagnostics-path }}
    
    - name: Upload diagnostics artifact
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.diagnostics-path }}/
        retention-days: ${{ inputs.retention-days }}
