name: Cleanup Stale SWA Environments
description: Finds and deletes Azure Static Web Apps staging environments for closed/merged PRs using Azure CLI

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  swa-name:
    description: Azure Static Web App name
    required: true
  resource-group:
    description: Azure resource group name
    required: true
  subscription-id:
    description: Azure subscription ID
    required: true
  dry-run:
    description: If true, only report what would be deleted without actually deleting
    required: false
    default: 'false'
  min-age-hours:
    description: Minimum age in hours before a closed PR environment is considered stale
    required: false
    default: '1'
  max-prs-to-check:
    description: Maximum number of closed PRs to check
    required: false
    default: '100'

outputs:
  deleted-count:
    description: Number of environments deleted
    value: ${{ steps.cleanup.outputs.deleted_count }}
  stale-prs:
    description: Comma-separated list of PR numbers with stale environments
    value: ${{ steps.cleanup.outputs.stale_prs }}

runs:
  using: composite
  steps:
    - name: List and cleanup stale SWA environments
      id: cleanup
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SWA_NAME: ${{ inputs.swa-name }}
        RESOURCE_GROUP: ${{ inputs.resource-group }}
        SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        DRY_RUN: ${{ inputs.dry-run }}
        MIN_AGE_HOURS: ${{ inputs.min-age-hours }}
      run: bash ${{ github.action_path }}/script.sh

    - name: Create cleanup summary
      if: always()
      shell: bash
      env:
        DELETED_COUNT: ${{ steps.cleanup.outputs.deleted_count || '0' }}
        STALE_COUNT: ${{ steps.find.outputs.stale_count || '0' }}
        STALE_PRS: ${{ steps.cleanup.outputs.stale_prs || steps.find.outputs.stale_prs || 'none' }}
        DRY_RUN: ${{ inputs.dry-run }}
        MIN_AGE_HOURS: ${{ inputs.min-age-hours }}
      run: bash ${{ github.action_path }}/generate-summary.sh
