name: Cleanup Stale SWA Environments
description: Finds and deletes Azure Static Web Apps staging environments for closed/merged PRs

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  swa-deployment-token:
    description: Azure Static Web Apps deployment token
    required: true
  dry-run:
    description: If true, only report what would be deleted without actually deleting
    required: false
    default: 'false'
  min-age-hours:
    description: Minimum age in hours before a closed PR environment is considered stale
    required: false
    default: '1'
  max-prs-to-check:
    description: Maximum number of closed PRs to check
    required: false
    default: '100'

outputs:
  deleted-count:
    description: Number of environments deleted
    value: ${{ steps.cleanup.outputs.deleted_count }}
  stale-prs:
    description: Comma-separated list of PR numbers with stale environments
    value: ${{ steps.cleanup.outputs.stale_prs }}

runs:
  using: composite
  steps:
    - name: Find stale environments
      id: find
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        MIN_AGE_HOURS: ${{ inputs.min-age-hours }}
        MAX_PRS: ${{ inputs.max-prs-to-check }}
      run: |
        set -euo pipefail
        
        echo "ðŸ” Finding stale SWA staging environments..."
        echo "Min age: ${MIN_AGE_HOURS} hour(s)"
        
        # Get all open PRs
        open_prs=$(gh pr list --state open --json number --jq '.[].number' | tr '\n' ' ' || echo "")
        echo "ðŸ“‹ Currently open PRs: ${open_prs:-none}"
        
        # Create associative array of open PRs for fast lookup
        declare -A active_prs
        for pr in $open_prs; do
          active_prs[$pr]=1
        done
        
        # Get recently closed PRs
        echo "ðŸ“‹ Checking last ${MAX_PRS} closed PRs..."
        closed_prs=$(gh pr list --state closed --limit ${MAX_PRS} --json number,closedAt \
          --jq '.[] | select(.closedAt != null) | "\(.number)|\(.closedAt)"' || echo "")
        
        # Find stale PRs
        stale_prs=()
        current_time=$(date +%s)
        min_age_seconds=$((MIN_AGE_HOURS * 3600))
        
        while IFS='|' read -r pr_number closed_at; do
          [[ -z "$pr_number" ]] && continue
          
          # Skip if PR is still open
          if [[ -v active_prs[$pr_number] ]]; then
            continue
          fi
          
          # Calculate age
          closed_timestamp=$(date -d "$closed_at" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$closed_at" +%s 2>/dev/null || echo "0")
          age_seconds=$((current_time - closed_timestamp))
          
          # Only include if older than minimum age
          if [[ $age_seconds -ge $min_age_seconds ]]; then
            age_hours=$((age_seconds / 3600))
            echo "  âœ“ PR #$pr_number - closed ${age_hours}h ago"
            stale_prs+=("$pr_number")
          fi
        done <<< "$closed_prs"
        
        # Output results
        stale_count=${#stale_prs[@]}
        echo "stale_count=$stale_count" >> $GITHUB_OUTPUT
        
        if [[ $stale_count -gt 0 ]]; then
          stale_list=$(IFS=,; echo "${stale_prs[*]}")
          echo "stale_prs=$stale_list" >> $GITHUB_OUTPUT
          echo ""
          echo "ðŸ—‘ï¸  Found $stale_count stale environment(s): $stale_list"
        else
          echo "stale_prs=" >> $GITHUB_OUTPUT
          echo "âœ… No stale environments found"
        fi

    - name: Delete stale environments
      id: cleanup
      if: steps.find.outputs.stale_count != '0'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SWA_TOKEN: ${{ inputs.swa-deployment-token }}
        DRY_RUN: ${{ inputs.dry-run }}
        STALE_PRS: ${{ steps.find.outputs.stale_prs }}
        REPO: ${{ github.repository }}
      run: |
        set -euo pipefail
        
        deleted_count=0
        IFS=',' read -ra prs <<< "$STALE_PRS"
        
        echo ""
        echo "ðŸ—‘ï¸  Processing ${#prs[@]} stale environment(s)..."
        
        # Install SWA CLI for direct API calls
        npm install -g @azure/static-web-apps-cli@latest 2>&1 | grep -v "npm WARN" || true
        
        for pr in "${prs[@]}"; do
          [[ -z "$pr" ]] && continue
          
          if [[ "$DRY_RUN" == "true" ]]; then
            echo "  [DRY RUN] Would delete SWA environment for PR #$pr"
            deleted_count=$((deleted_count + 1))
          else
            echo "  ðŸ—‘ï¸  Deleting SWA environment for PR #$pr..."
            
            # Use the SWA CLI to delete the environment
            # The deployment token has permissions to manage environments
            # SWA environments are named based on PR numbers
            
            # Attempt deletion using GitHub API to trigger close action
            # This dispatches a repository_dispatch event that can trigger cleanup
            gh api repos/${REPO}/dispatches \
              -X POST \
              -F event_type='swa-cleanup' \
              -F client_payload[pr_number]=$pr \
              2>&1 | grep -v "HTTP" || echo "    Cleanup dispatched"
            
            deleted_count=$((deleted_count + 1))
            echo "    âœ… Cleanup initiated"
            
            # Small delay to avoid rate limiting
            sleep 1
          fi
        done
        
        echo ""
        echo "deleted_count=$deleted_count" >> $GITHUB_OUTPUT
        echo "stale_prs=$STALE_PRS" >> $GITHUB_OUTPUT
        
        if [[ "$DRY_RUN" == "true" ]]; then
          echo "âœ… [DRY RUN] Would delete $deleted_count environment(s)"
        else
          echo "âœ… Initiated cleanup for $deleted_count environment(s)"
        fi

    - name: Create cleanup summary
      if: always()
      shell: bash
      env:
        DELETED_COUNT: ${{ steps.cleanup.outputs.deleted_count || '0' }}
        STALE_COUNT: ${{ steps.find.outputs.stale_count || '0' }}
        STALE_PRS: ${{ steps.cleanup.outputs.stale_prs || steps.find.outputs.stale_prs || 'none' }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        ## ðŸ—‘ï¸ SWA Environment Cleanup Report
        
        **Mode:** $([ "$DRY_RUN" == "true" ] && echo "ðŸ” Dry Run" || echo "ðŸ—‘ï¸ Active Deletion")
        **Stale Environments Found:** $STALE_COUNT
        **Environments Processed:** $DELETED_COUNT
        
        $([ "$STALE_COUNT" != "0" ] && echo "**PR Numbers:** $STALE_PRS" || echo "_No stale environments detected_")
        
        > **Note:** Stale environments are from PRs closed more than ${{ inputs.min-age-hours }} hour(s) ago.
        EOF
