name: Cleanup Stale SWA Environments
description: Finds and deletes Azure Static Web Apps staging environments for closed/merged PRs

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  swa-deployment-token:
    description: Azure Static Web Apps deployment token
    required: true
  dry-run:
    description: If true, only report what would be deleted without actually deleting
    required: false
    default: 'false'

outputs:
  deleted-count:
    description: Number of environments deleted
    value: ${{ steps.cleanup.outputs.deleted_count }}
  stale-environments:
    description: JSON array of stale environment names
    value: ${{ steps.cleanup.outputs.stale_environments }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Azure CLI
      shell: bash
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Find and cleanup stale SWA environments
      id: cleanup
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SWA_TOKEN: ${{ inputs.swa-deployment-token }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        set -euo pipefail
        
        echo "ðŸ” Finding stale SWA staging environments..."
        
        # Get all open PRs
        open_prs=$(gh pr list --state open --json number --jq '.[].number' || echo "")
        echo "Open PRs: ${open_prs:-none}"
        
        # Get all merged/closed PRs from the last 30 days that might have environments
        recent_closed_prs=$(gh pr list --state closed --limit 100 --json number --jq '.[].number' || echo "")
        
        # Combine into a set of "potentially active" PR numbers
        declare -A active_prs
        for pr in $open_prs; do
          active_prs[$pr]=1
        done
        
        echo "Active PRs: ${!active_prs[@]:-none}"
        
        # We can't easily list SWA environments without Azure credentials
        # Instead, we'll attempt to close environments for recently closed PRs
        # Azure SWA automatically names staging environments based on PR number
        
        deleted_count=0
        stale_envs=()
        
        for pr in $recent_closed_prs; do
          # Skip if PR is still open
          if [[ -v active_prs[$pr] ]]; then
            echo "â­ï¸  Skipping PR #$pr (still open)"
            continue
          fi
          
          # Check if PR was closed more than 1 hour ago to avoid race conditions
          pr_closed_at=$(gh pr view $pr --json closedAt --jq '.closedAt' || echo "")
          if [[ -z "$pr_closed_at" ]]; then
            continue
          fi
          
          # Calculate age in seconds
          closed_timestamp=$(date -d "$pr_closed_at" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$pr_closed_at" +%s 2>/dev/null || echo "0")
          current_timestamp=$(date +%s)
          age_seconds=$((current_timestamp - closed_timestamp))
          
          # Only cleanup if closed more than 1 hour ago
          if [[ $age_seconds -lt 3600 ]]; then
            echo "â­ï¸  Skipping PR #$pr (closed less than 1 hour ago)"
            continue
          fi
          
          echo "ðŸ—‘ï¸  Found stale environment for PR #$pr (closed $(($age_seconds / 3600)) hours ago)"
          stale_envs+=("pr-$pr")
          
          if [[ "$DRY_RUN" == "true" ]]; then
            echo "   [DRY RUN] Would delete staging environment for PR #$pr"
          else
            # Attempt to close the environment
            # Note: This will fail silently if the environment doesn't exist
            echo "   Attempting to close SWA environment for PR #$pr..."
            
            # We need to trigger the SWA close action through the GitHub API
            # For now, we'll create a marker file that the workflow can use
            echo "$pr" >> /tmp/stale_prs_to_cleanup.txt
            ((deleted_count++))
          fi
        done
        
        echo "deleted_count=$deleted_count" >> $GITHUB_OUTPUT
        
        # Convert array to JSON
        stale_json=$(printf '%s\n' "${stale_envs[@]}" | jq -R . | jq -s .)
        echo "stale_environments=$stale_json" >> $GITHUB_OUTPUT
        
        echo "âœ… Cleanup complete: $deleted_count stale environments identified"
        
        # Save list for the workflow to process
        if [[ -f /tmp/stale_prs_to_cleanup.txt ]]; then
          cat /tmp/stale_prs_to_cleanup.txt
        fi

    - name: Create cleanup report
      shell: bash
      env:
        DELETED_COUNT: ${{ steps.cleanup.outputs.deleted_count }}
        STALE_ENVS: ${{ steps.cleanup.outputs.stale_environments }}
      run: |
        cat >> $GITHUB_STEP_SUMMARY << 'EOF'
        ## ðŸ—‘ï¸ SWA Environment Cleanup Report
        
        **Environments Processed:** ${{ env.DELETED_COUNT }}
        
        ### Stale Environments
        ${{ env.STALE_ENVS }}
        
        > **Note:** Stale environments are from PRs that were closed more than 1 hour ago.
        > The Azure SWA action will handle the actual deletion.
        EOF
