name: Cleanup Stale SWA Environments
description: Finds and deletes Azure Static Web Apps staging environments for closed/merged PRs using Azure CLI

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  swa-name:
    description: Azure Static Web App name
    required: true
  resource-group:
    description: Azure resource group name
    required: true
  subscription-id:
    description: Azure subscription ID
    required: true
  dry-run:
    description: If true, only report what would be deleted without actually deleting
    required: false
    default: 'false'
  min-age-hours:
    description: Minimum age in hours before a closed PR environment is considered stale
    required: false
    default: '1'
  max-prs-to-check:
    description: Maximum number of closed PRs to check
    required: false
    default: '100'

outputs:
  deleted-count:
    description: Number of environments deleted
    value: ${{ steps.cleanup.outputs.deleted_count }}
  stale-prs:
    description: Comma-separated list of PR numbers with stale environments
    value: ${{ steps.cleanup.outputs.stale_prs }}

runs:
  using: composite
  steps:
    - name: Find stale environments
      id: find
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        MIN_AGE_HOURS: ${{ inputs.min-age-hours }}
        MAX_PRS: ${{ inputs.max-prs-to-check }}
      run: |
        set -euo pipefail
        
        echo "🔍 Finding stale SWA staging environments..."
        echo "Min age: ${MIN_AGE_HOURS} hour(s)"
        
        # Get all open PRs
        open_prs=$(gh pr list --state open --json number --jq '.[].number' | tr '\n' ' ' || echo "")
        echo "📋 Currently open PRs: ${open_prs:-none}"
        
        # Create associative array of open PRs for fast lookup
        declare -A active_prs
        for pr in $open_prs; do
          active_prs[$pr]=1
        done
        
        # Get recently closed PRs
        echo "📋 Checking last ${MAX_PRS} closed PRs..."
        closed_prs=$(gh pr list --state closed --limit ${MAX_PRS} --json number,closedAt \
          --jq '.[] | select(.closedAt != null) | "\(.number)|\(.closedAt)"' || echo "")
        
        # Find stale PRs
        stale_prs=()
        current_time=$(date +%s)
        min_age_seconds=$((MIN_AGE_HOURS * 3600))
        
        while IFS='|' read -r pr_number closed_at; do
          [[ -z "$pr_number" ]] && continue
          
          # Skip if PR is still open
          if [[ -v active_prs[$pr_number] ]]; then
            continue
          fi
          
          # Calculate age
          closed_timestamp=$(date -d "$closed_at" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$closed_at" +%s 2>/dev/null || echo "0")
          age_seconds=$((current_time - closed_timestamp))
          
          # Only include if older than minimum age
          if [[ $age_seconds -ge $min_age_seconds ]]; then
            age_hours=$((age_seconds / 3600))
            echo "  ✓ PR #$pr_number - closed ${age_hours}h ago"
            stale_prs+=("$pr_number")
          fi
        done <<< "$closed_prs"
        
        # Output results
        stale_count=${#stale_prs[@]}
        echo "stale_count=$stale_count" >> $GITHUB_OUTPUT
        
        if [[ $stale_count -gt 0 ]]; then
          stale_list=$(IFS=,; echo "${stale_prs[*]}")
          echo "stale_prs=$stale_list" >> $GITHUB_OUTPUT
          echo ""
          echo "🗑️  Found $stale_count stale environment(s): $stale_list"
        else
          echo "stale_prs=" >> $GITHUB_OUTPUT
          echo "✅ No stale environments found"
        fi

    - name: Delete stale environments using Azure CLI
      id: cleanup
      if: steps.find.outputs.stale_count != '0'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SWA_NAME: ${{ inputs.swa-name }}
        RESOURCE_GROUP: ${{ inputs.resource-group }}
        SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        DRY_RUN: ${{ inputs.dry-run }}
        STALE_PRS: ${{ steps.find.outputs.stale_prs }}
        REPO: ${{ github.repository }}
      run: |
        set -euo pipefail
        
        # Set subscription context
        echo "🔧 Setting Azure subscription context..."
        az account set --subscription "$SUBSCRIPTION_ID"
        
        # List all SWA environments/builds
        echo "📋 Listing SWA environments for $SWA_NAME..."
        environments=$(az staticwebapp environment list \
          -n "$SWA_NAME" \
          -g "$RESOURCE_GROUP" \
          -o json 2>/dev/null || echo "[]")
        
        if [[ "$environments" == "[]" ]]; then
          echo "⚠️  No environments found or unable to list environments"
          echo "deleted_count=0" >> $GITHUB_OUTPUT
          echo "stale_prs=$STALE_PRS" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        deleted_count=0
        IFS=',' read -ra prs <<< "$STALE_PRS"
        
        echo ""
        echo "🗑️  Processing ${#prs[@]} stale PR(s)..."
        echo ""
        
        for pr in "${prs[@]}"; do
          [[ -z "$pr" ]] && continue
          
          echo "🔍 Looking for environment matching PR #$pr..."
          
          # Find environment(s) matching this PR
          # Match by: pullRequestTitle is set AND (buildId == PR or hostname contains "-PR.")
          matched_envs=$(echo "$environments" | jq -r --arg pr "$pr" '
            .[] | 
            select(
              (.properties.pullRequestTitle != null and .properties.pullRequestTitle != "") and
              (
                (.properties.buildId == $pr) or
                (.properties.hostname | tostring | contains("-" + $pr + "."))
              )
            ) |
            .name
          ' 2>/dev/null || echo "")
          
          if [[ -z "$matched_envs" ]]; then
            echo "  ⚠️  No environment found for PR #$pr (may already be deleted)"
            continue
          fi
          
          # Process each matched environment
          while IFS= read -r env_name; do
            [[ -z "$env_name" ]] && continue
            
            # Safety check: never delete "default" (production)
            if [[ "$env_name" == "default" ]]; then
              echo "  🛑 SKIPPED: Refusing to delete production environment 'default'"
              continue
            fi
            
            if [[ "$DRY_RUN" == "true" ]]; then
              echo "  [DRY RUN] Would delete environment: $env_name (PR #$pr)"
              deleted_count=$((deleted_count + 1))
            else
              echo "  🗑️  Deleting environment: $env_name (PR #$pr)..."
              
              if az staticwebapp environment delete \
                -n "$SWA_NAME" \
                -g "$RESOURCE_GROUP" \
                --environment-name "$env_name" \
                --yes \
                2>&1 | grep -v "WARNING"; then
                
                echo "    ✅ Successfully deleted environment: $env_name"
                deleted_count=$((deleted_count + 1))
              else
                echo "    ❌ Failed to delete environment: $env_name"
              fi
            fi
          done <<< "$matched_envs"
        done
        
        echo ""
        echo "deleted_count=$deleted_count" >> $GITHUB_OUTPUT
        echo "stale_prs=$STALE_PRS" >> $GITHUB_OUTPUT
        
        if [[ "$DRY_RUN" == "true" ]]; then
          echo "✅ [DRY RUN] Would delete $deleted_count environment(s)"
        else
          echo "✅ Deleted $deleted_count environment(s)"
        fi

    - name: Create cleanup summary
      if: always()
      shell: bash
      env:
        DELETED_COUNT: ${{ steps.cleanup.outputs.deleted_count || '0' }}
        STALE_COUNT: ${{ steps.find.outputs.stale_count || '0' }}
        STALE_PRS: ${{ steps.cleanup.outputs.stale_prs || steps.find.outputs.stale_prs || 'none' }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        ## 🗑️ SWA Environment Cleanup Report
        
        **Mode:** $([ "$DRY_RUN" == "true" ] && echo "🔍 Dry Run" || echo "🗑️ Active Deletion")
        **Stale Environments Found:** $STALE_COUNT
        **Environments Processed:** $DELETED_COUNT
        
        $([ "$STALE_COUNT" != "0" ] && echo "**PR Numbers:** $STALE_PRS" || echo "_No stale environments detected_")
        
        > **Note:** Stale environments are from PRs closed more than ${{ inputs.min-age-hours }} hour(s) ago.
        EOF
