# =============================================================================
# Pre-Deployment Validation Action
# =============================================================================
# Validates deployment manifests BEFORE Argo CD deploys them.
# Catches common issues in <30 seconds instead of 3+ minute timeouts.
#
# Validations performed:
#   - Kustomize builds successfully (catches YAML syntax errors)
#   - YAML structure is valid (kubectl apply --dry-run)
#   - Resource requests fit within namespace quota
#   - Container images exist in ACR
#   - Required secrets/ServiceAccounts exist
#   - Resource dependencies are valid (pods reference existing resources)
#
# Usage:
#   - uses: ./.github/actions/deployment-validate
#     with:
#       overlay-path: k8s/overlays/preview
#       target-namespace: preview-pr-110
#       acr-login-server: acrytsummprd.azurecr.io
#
# Optional - Query AKS for actual quota:
#   - uses: ./.github/actions/deployment-validate
#     with:
#       overlay-path: k8s/overlays/preview
#       target-namespace: preview-pr-110
#       acr-login-server: acrytsummprd.azurecr.io
#       query-aks: 'true'
#       aks-resource-group: rg-yt-summarizer-prod
#       aks-cluster-name: aks-yt-summarizer-prod
# =============================================================================

name: Validate Deployment
description: Pre-deployment validation for Kubernetes manifests

inputs:
  overlay-path:
    description: "Kustomize overlay path to validate (e.g., k8s/overlays/preview)"
    required: true

  target-namespace:
    description: "Target namespace for deployment (e.g., preview-pr-110)"
    required: true

  acr-login-server:
    description: "Azure Container Registry login server (e.g., acrytsummprd.azurecr.io)"
    required: false
    default: "acrytsummprd.azurecr.io"

  query-aks:
    description: "Query AKS cluster for actual resource quotas (requires Azure login)"
    required: false
    default: "false"

  aks-resource-group:
    description: "AKS resource group (required if query-aks=true)"
    required: false

  aks-cluster-name:
    description: "AKS cluster name (required if query-aks=true)"
    required: false

  max-cpu-millicores:
    description: "Maximum CPU in millicores (default: 1500 for preview, ignored if query-aks=true)"
    required: false
    default: "1500"

  max-memory-mi:
    description: "Maximum memory in Mi (default: 2560 for preview, ignored if query-aks=true)"
    required: false
    default: "2560"

  skip-image-validation:
    description: "Skip validation that images exist in ACR (useful for local testing)"
    required: false
    default: "false"

  skip-secret-validation:
    description: "Skip validation of secrets/ServiceAccounts (useful for new environments)"
    required: false
    default: "false"

outputs:
  validation-passed:
    description: "Boolean indicating if validation passed"
    value: ${{ steps.validate.outputs.validation-passed }}

  errors:
    description: "Number of validation errors found"
    value: ${{ steps.validate.outputs.errors }}

  warnings:
    description: "Number of validation warnings found"
    value: ${{ steps.validate.outputs.warnings }}

runs:
  using: composite
  steps:
    - name: Validate deployment manifests
      id: validate
      shell: bash
      env:
        OVERLAY_PATH: ${{ inputs.overlay-path }}
        TARGET_NAMESPACE: ${{ inputs.target-namespace }}
        ACR_LOGIN_SERVER: ${{ inputs.acr-login-server }}
        QUERY_AKS: ${{ inputs.query-aks }}
        AKS_RESOURCE_GROUP: ${{ inputs.aks-resource-group }}
        AKS_CLUSTER_NAME: ${{ inputs.aks-cluster-name }}
        MAX_CPU_MILLICORES: ${{ inputs.max-cpu-millicores }}
        MAX_MEMORY_MI: ${{ inputs.max-memory-mi }}
        SKIP_IMAGE_VALIDATION: ${{ inputs.skip-image-validation }}
        SKIP_SECRET_VALIDATION: ${{ inputs.skip-secret-validation }}
      run: |
        set -euo pipefail

        echo "::group::📋 Pre-Deployment Validation"
        echo "Overlay: $OVERLAY_PATH"
        echo "Namespace: $TARGET_NAMESPACE"
        echo "ACR: $ACR_LOGIN_SERVER"
        echo "Query AKS: $QUERY_AKS"
        [[ "$QUERY_AKS" == "true" ]] && echo "AKS: $AKS_RESOURCE_GROUP/$AKS_CLUSTER_NAME"
        [[ "$QUERY_AKS" != "true" ]] && echo "Max CPU: ${MAX_CPU_MILLICORES}m, Max Memory: ${MAX_MEMORY_MI}Mi"
        echo "::endgroup::"
        echo ""

        # Export variables for the script
        export OVERLAY_PATH TARGET_NAMESPACE ACR_LOGIN_SERVER
        export QUERY_AKS AKS_RESOURCE_GROUP AKS_CLUSTER_NAME
        export MAX_CPU_MILLICORES MAX_MEMORY_MI
        export SKIP_IMAGE_VALIDATION SKIP_SECRET_VALIDATION

        # Run validation script
        if bash "${{ github.action_path }}/../../../scripts/ci/lib/validate-deployment.sh" \
          "$OVERLAY_PATH" \
          "$TARGET_NAMESPACE" \
          "$ACR_LOGIN_SERVER"; then
          echo ""
          echo "validation-passed=true" >> "$GITHUB_OUTPUT"
          echo "errors=0" >> "$GITHUB_OUTPUT"
          echo "warnings=0" >> "$GITHUB_OUTPUT"
          echo "✅ All validations passed!"
          exit 0
        else
          echo ""
          echo "validation-passed=false" >> "$GITHUB_OUTPUT"
          echo "::error::Pre-deployment validation failed. See logs above for details."
          exit 1
        fi
