# Reusable Azure AKS setup action
# Authenticates to Azure via OIDC and sets AKS cluster context

name: 'Setup AKS'
description: 'Login to Azure via OIDC and set AKS cluster context for kubectl operations'

inputs:
  azure-client-id:
    description: 'Azure Client ID for OIDC authentication'
    required: true
  azure-tenant-id:
    description: 'Azure Tenant ID for OIDC authentication'
    required: true
  azure-subscription-id:
    description: 'Azure Subscription ID'
    required: true
  resource-group:
    description: 'Azure Resource Group containing the AKS cluster'
    required: true
  cluster-name:
    description: 'AKS cluster name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ inputs.resource-group }}
        cluster-name: ${{ inputs.cluster-name }}
