# Reusable Docker build and push action
# Builds Docker images with caching and pushes to registry

name: 'Docker Build and Push'
description: 'Build and push Docker image with caching'

inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  image-name:
    description: 'Image name (without registry)'
    required: true
  image-tag:
    description: 'Image tag'
    required: true
  registry:
    description: 'Container registry URL'
    required: true
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'
  cache-name:
    description: 'Cache name for the service'
    required: true
  add-latest-tag:
    description: 'Also tag as latest'
    required: false
    default: 'false'

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  build_duration:
    description: 'Build duration in seconds'
    value: ${{ steps.finish.outputs.build_duration }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Record build start
      id: start
      shell: bash
      run: echo "started_at=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build and push image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: |
          ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          ${{ inputs.add-latest-tag == 'true' && format('{0}/{1}:latest', inputs.registry, inputs.image-name) || '' }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        cache-from: |
          type=registry,ref=${{ inputs.registry }}/yt-summarizer-cache-${{ inputs.cache-name }}:latest
          type=gha
        cache-to: |
          type=registry,ref=${{ inputs.registry }}/yt-summarizer-cache-${{ inputs.cache-name }}:latest,mode=max
          type=gha,mode=max
        platforms: linux/amd64

    - name: Record build finish
      id: finish
      shell: bash
      run: |
        END=$(date +%s)
        START=${{ steps.start.outputs.started_at }}
        DURATION=$((END - START))
        echo "build_duration=${DURATION}" >> $GITHUB_OUTPUT
        echo "Build duration: ${DURATION}s"
