name: Verify TLS Certificate
description: Verify TLS certificate is valid and not expired

inputs:
  host:
    description: Hostname to verify
    required: true

runs:
  using: composite
  steps:
    - name: Verify certificate
      shell: bash
      run: ${{ github.action_path }}/verify-tls.sh "${{ inputs.host }}"
