name: Verify TLS Certificate
description: Verify TLS certificate is valid and not expired

inputs:
  host:
    description: Hostname to verify
    required: true

runs:
  using: composite
  steps:
    - name: Verify certificate
      shell: bash
      run: |
        API_HOST="${{ inputs.host }}"
        
        if [ -z "$API_HOST" ]; then
          echo "::warning::No API host provided - skipping certificate verification"
          exit 0
        fi
        
        echo "Verifying certificate for ${API_HOST}"
        
        # Use openssl to check certificate chain and validity
        CERT_OUTPUT=$(echo | openssl s_client -connect ${API_HOST}:443 -servername ${API_HOST} 2>/dev/null | openssl x509 -noout -text)
        
        if [ $? -ne 0 ]; then
          echo "::error::Failed to retrieve certificate from ${API_HOST}"
          exit 1
        fi
        
        # Check if certificate is not expired
        if echo "$CERT_OUTPUT" | grep -q "Not Before:" && echo "$CERT_OUTPUT" | grep -q "Not After:"; then
          echo "✅ Certificate dates found"
        else
          echo "::error::Certificate missing validity dates"
          exit 1
        fi
        
        # Check for Let's Encrypt R3 intermediate
        if echo "$CERT_OUTPUT" | grep -q "Issuer: C=US, O=Let's Encrypt, CN=R3"; then
          echo "✅ Let's Encrypt R3 intermediate certificate detected"
        else
          echo "::warning::Let's Encrypt R3 intermediate not found in certificate chain"
        fi
        
        # Check certificate validity period
        NOT_BEFORE=$(echo "$CERT_OUTPUT" | grep "Not Before:" | sed 's/.*Not Before: //')
        NOT_AFTER=$(echo "$CERT_OUTPUT" | grep "Not After:" | sed 's/.*Not After: //')
        
        echo "Certificate valid from: ${NOT_BEFORE}"
        echo "Certificate valid until: ${NOT_AFTER}"
        
        # Check if certificate is currently valid
        CURRENT_TIME=$(date +%s)
        NOT_AFTER_EPOCH=$(date -d "$NOT_AFTER" +%s 2>/dev/null || date -j -f "%b %d %H:%M:%S %Y %Z" "$NOT_AFTER" +%s 2>/dev/null)
        
        if [ -n "$NOT_AFTER_EPOCH" ] && [ $CURRENT_TIME -lt $NOT_AFTER_EPOCH ]; then
          echo "✅ Certificate is not expired"
        else
          echo "::error::Certificate appears to be expired or invalid date format"
          exit 1
        fi
        
        echo "✅ Certificate verification passed"
