name: Verify Kubernetes Deployment
description: Verify that Kubernetes deployments are using the expected image tag

inputs:
  namespace:
    description: Kubernetes namespace
    required: true

  deployments:
    description: 'Comma-separated deployment names (e.g., "api,transcribe-worker,summarize-worker")'
    required: true

  expected-tag:
    description: Expected image tag
    required: true

  registry:
    description: Container registry (e.g., acrytsummprd.azurecr.io)
    required: true

  image-name:
    description: Image name without tag (e.g., yt-summarizer-api or yt-summarizer-workers)
    required: true

  wait-for-ready:
    description: Wait for deployments to be ready before verifying
    required: false
    default: 'true'

  timeout-seconds:
    description: Maximum time to wait for deployments to be ready
    required: false
    default: '300'

  fail-on-mismatch:
    description: Fail if any deployment has a mismatched image
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Verify deployment images
      shell: bash
      env:
        NAMESPACE: ${{ inputs.namespace }}
        DEPLOYMENTS: ${{ inputs.deployments }}
        EXPECTED_TAG: ${{ inputs.expected-tag }}
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ inputs.image-name }}
        WAIT_FOR_READY: ${{ inputs.wait-for-ready }}
        TIMEOUT_SECONDS: ${{ inputs.timeout-seconds }}
        FAIL_ON_MISMATCH: ${{ inputs.fail-on-mismatch }}
      run: bash ${{ github.action_path }}/verify-deployments.sh
