name: 'Verify Azure OIDC Credentials'
description: 'Verifies that required Azure OIDC credentials are configured'
inputs:
  client-id:
    description: 'Azure client ID to verify'
    required: true
  tenant-id:
    description: 'Azure tenant ID to verify'
    required: true
  subscription-id:
    description: 'Azure subscription ID to verify'
    required: true
runs:
  using: composite
  steps:
    - name: Verify Azure credentials
      shell: bash
      env:
        CLIENT_ID: ${{ inputs.client-id }}
        TENANT_ID: ${{ inputs.tenant-id }}
        SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
      run: bash ${{ github.action_path }}/script.sh
