name: Check PR Open Status
description: |
  Checks if a PR is still open and fails gracefully if closed.
  Use this at the start of long-running jobs to avoid wasting resources on closed PRs.

inputs:
  pr-number:
    description: 'Pull request number to check'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}

outputs:
  is-open:
    description: 'Whether the PR is open (true/false)'
    value: ${{ steps.check.outputs.is-open }}
  pr-state:
    description: 'The state of the PR (open/closed/merged)'
    value: ${{ steps.check.outputs.pr-state }}

runs:
  using: composite
  steps:
    - name: Check if PR is still open
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        echo "ðŸ” Checking if PR #${PR_NUMBER} is still open..."

        # Fetch PR state using GitHub CLI
        PR_DATA=$(gh pr view "${PR_NUMBER}" --json state,closed,merged --repo "${{ github.repository }}" 2>/dev/null || echo "")

        if [ -z "$PR_DATA" ]; then
          echo "::error::Failed to fetch PR #${PR_NUMBER}"
          echo "is-open=unknown" >> "$GITHUB_OUTPUT"
          echo "pr-state=unknown" >> "$GITHUB_OUTPUT"
          exit 1
        fi

        STATE=$(echo "$PR_DATA" | jq -r '.state')
        CLOSED=$(echo "$PR_DATA" | jq -r '.closed')
        MERGED=$(echo "$PR_DATA" | jq -r '.merged')

        echo "ðŸ“Š PR State: $STATE (closed=$CLOSED, merged=$MERGED)"

        # Determine if PR is open
        if [ "$STATE" = "OPEN" ]; then
          echo "âœ… PR #${PR_NUMBER} is still open - continuing deployment"
          echo "is-open=true" >> "$GITHUB_OUTPUT"
          echo "pr-state=open" >> "$GITHUB_OUTPUT"
        else
          if [ "$MERGED" = "true" ]; then
            echo "::notice::PR #${PR_NUMBER} has been merged - cancelling preview deployment"
            echo "is-open=false" >> "$GITHUB_OUTPUT"
            echo "pr-state=merged" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::PR #${PR_NUMBER} has been closed - cancelling preview deployment"
            echo "is-open=false" >> "$GITHUB_OUTPUT"
            echo "pr-state=closed" >> "$GITHUB_OUTPUT"
          fi

          # Exit with error to stop the job
          echo "::error::Stopping job because PR is no longer open"
          exit 1
        fi
