name: Check PR Open Status
description: |
  Checks if a PR is still open and fails gracefully if closed.
  Use this at the start of long-running jobs to avoid wasting resources on closed PRs.

inputs:
  pr-number:
    description: 'Pull request number to check'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository in the format owner/repo'
    required: false
    default: ''

outputs:
  is-open:
    description: 'Whether the PR is open (true/false)'
    value: ${{ steps.check.outputs.is-open }}
  pr-state:
    description: 'The state of the PR (open/closed/merged)'
    value: ${{ steps.check.outputs.pr-state }}

runs:
  using: composite
  steps:
    - name: Check if PR is still open
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
        REPOSITORY: ${{ inputs.repository }}
      run: |
        echo "ðŸ” Checking if PR #${PR_NUMBER} is still open..."

        # Determine repository - use input if provided, otherwise detect from git remote
        if [ -z "$REPOSITORY" ]; then
          REPOSITORY=$(git remote get-url origin | sed -E 's|https://github.com/||' | sed -E 's|git@github.com:||' | sed -E 's|\.git$||')
          echo "ðŸ“ Detected repository: $REPOSITORY"
        fi

        # Fetch PR state using GitHub CLI (redirect stderr to suppress error messages)
        set +e  # Don't exit on error
        PR_DATA=$(gh pr view "${PR_NUMBER}" --json state,closed,merged --repo "${REPOSITORY}" 2>/dev/null)
        PR_FETCH_EXIT_CODE=$?
        set -e  # Re-enable exit on error

        # Check if PR data fetch failed
        if [ $PR_FETCH_EXIT_CODE -ne 0 ] || [ -z "$PR_DATA" ]; then
          echo "::warning::Could not fetch PR #${PR_NUMBER} status - assuming PR is still open to avoid false failures"
          echo "This may occur if the PR is being created/updated or there's a temporary API issue"
          echo "is-open=true" >> "$GITHUB_OUTPUT"
          echo "pr-state=unknown" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Validate JSON before parsing
        if ! echo "$PR_DATA" | jq empty 2>/dev/null; then
          echo "::warning::Received invalid JSON from gh pr view - assuming PR is still open"
          echo "is-open=true" >> "$GITHUB_OUTPUT"
          echo "pr-state=unknown" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        STATE=$(echo "$PR_DATA" | jq -r '.state')
        CLOSED=$(echo "$PR_DATA" | jq -r '.closed')
        MERGED=$(echo "$PR_DATA" | jq -r '.merged')

        echo "ðŸ“Š PR State: $STATE (closed=$CLOSED, merged=$MERGED)"

        # Determine if PR is open
        if [ "$STATE" = "OPEN" ]; then
          echo "âœ… PR #${PR_NUMBER} is still open - continuing deployment"
          echo "is-open=true" >> "$GITHUB_OUTPUT"
          echo "pr-state=open" >> "$GITHUB_OUTPUT"
        else
          if [ "$MERGED" = "true" ]; then
            echo "::notice::PR #${PR_NUMBER} has been merged - cancelling preview deployment"
            echo "is-open=false" >> "$GITHUB_OUTPUT"
            echo "pr-state=merged" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::PR #${PR_NUMBER} has been closed - cancelling preview deployment"
            echo "is-open=false" >> "$GITHUB_OUTPUT"
            echo "pr-state=closed" >> "$GITHUB_OUTPUT"
          fi

          # Exit with error to stop the job
          echo "::error::Stopping job because PR is no longer open"
          exit 1
        fi
