name: Run pytest
description: Executes pytest with standardized configuration

inputs:
  working-directory:
    description: Directory containing tests to run
    required: true
  pytest-args:
    description: Additional pytest arguments
    required: false
    default: '-v --tb=short'
  parallel:
    description: Run tests in parallel with pytest-xdist
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run pytest
      shell: bash
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        PARALLEL: ${{ inputs.parallel }}
        PYTEST_ARGS: ${{ inputs.pytest-args }}
      run: bash ${{ github.action_path }}/script.sh
