name: Run pytest
description: Executes pytest with standardized configuration

inputs:
  working-directory:
    description: Directory containing tests to run
    required: true
  pytest-args:
    description: Additional pytest arguments (excluding -m marker expression)
    required: false
    default: '-v --tb=short'
  markers:
    description: Marker expression for -m option (e.g., "not integration and not live")
    required: false
    default: ''
  parallel:
    description: Run tests in parallel with pytest-xdist
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run pytest
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PYTEST_ARGS: ${{ inputs.pytest-args }}
        MARKERS: ${{ inputs.markers }}
        PARALLEL: ${{ inputs.parallel }}
      run: |
        # Build pytest command
        CMD="python -m pytest"
        if [ "$PARALLEL" = "true" ]; then
          CMD="$CMD -n auto"
        fi
        CMD="$CMD tests/"
        if [ -n "$PYTEST_ARGS" ]; then
          CMD="$CMD $PYTEST_ARGS"
        fi
        if [ -n "$MARKERS" ]; then
          CMD="$CMD -m \"$MARKERS\""
        fi
        
        echo "Running: $CMD"
        eval "$CMD"
