name: 'Terraform Plan'
description: 'Runs terraform plan and captures output for PR comments'
inputs:
  working-directory:
    description: 'Working directory for terraform commands'
    required: true
  subscription-id:
    description: 'Azure subscription ID'
    required: true
  sql-admin-password:
    description: 'SQL admin password'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  cloudflare-api-token:
    description: 'Cloudflare API token'
    required: true
outputs:
  plan_output:
    description: 'Raw terraform plan output'
    value: ${{ steps.plan.outputs.plan_output }}
  formatted_plan:
    description: 'Formatted plan for PR comments'
    value: ${{ steps.format.outputs.formatted_plan }}
  plan_summary:
    description: 'JSON summary of plan changes'
    value: ${{ steps.format.outputs.plan_summary }}
  outcome:
    description: 'Plan outcome (success/failure)'
    value: ${{ steps.plan.outcome }}
runs:
  using: composite
  steps:
    - name: Initialize Terraform with backend
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        AUTH0_DOMAIN: ${{ env.AUTH0_DOMAIN }}
        AUTH0_CLIENT_ID: ${{ env.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ env.AUTH0_CLIENT_SECRET }}
        ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
        ARM_USE_OIDC: ${{ env.ARM_USE_OIDC }}
      run: |
        # Re-initialize with backend enabled (validation step used -backend=false)
        terraform init -backend=true -reconfigure

    - name: Run terraform plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        SQL_ADMIN_PASSWORD: ${{ inputs.sql-admin-password }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        AUTH0_DOMAIN: ${{ env.AUTH0_DOMAIN }}
      run: ${{ github.action_path }}/run-terraform-plan.sh
      # Do NOT use continue-on-error - we want the step to FAIL when plan fails
      # Post-plan steps use 'if: always()' to run even on failure

    - name: Get JSON plan
      id: format
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      # Always run to provide output even if plan failed
      # Returns empty summary with error flag if tfplan doesn't exist
      run: ${{ github.action_path }}/parse-terraform-plan.sh
      continue-on-error: true
