name: 'Terraform Plan'
description: 'Runs terraform plan and captures output for PR comments'
inputs:
  working-directory:
    description: 'Working directory for terraform commands'
    required: true
  subscription-id:
    description: 'Azure subscription ID'
    required: true
  sql-admin-password:
    description: 'SQL admin password'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  cloudflare-api-token:
    description: 'Cloudflare API token'
    required: true
outputs:
  plan_output:
    description: 'Raw terraform plan output'
    value: ${{ steps.plan.outputs.plan_output }}
  plan_json_path:
    description: 'Absolute path to plan.json on disk (avoids GITHUB_OUTPUT size limits)'
    value: ${{ steps.format.outputs.plan_json_path }}
  plan_summary:
    description: 'JSON summary of plan changes'
    value: ${{ steps.format.outputs.plan_summary }}
  outcome:
    description: 'Plan outcome (success/failure)'
    value: ${{ steps.plan.outcome }}
runs:
  using: composite
  steps:
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init -input=false -no-color

    - name: Run terraform plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        SQL_ADMIN_PASSWORD: ${{ inputs.sql-admin-password }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        AUTH0_DOMAIN: ${{ env.AUTH0_DOMAIN }}
      run: ${{ github.action_path }}/run-terraform-plan.sh

    - name: Get JSON plan
      id: format
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ github.action_path }}/parse-terraform-plan.sh
