# Scan Python Code Security
# Runs comprehensive Python security scans
# Uses: bandit (security scanning), mypy (type checking)
# Note: Linting (ruff) is handled separately in the lint-python job

name: 'Scan Python Code Security'
description: 'Run Python security and type checking scans'

inputs:
  service-path:
    description: 'Path to the service directory (e.g., services/api)'
    required: true
  check-types:
    description: 'Run mypy type checking'
    required: false
    default: 'false'
  check-security:
    description: 'Run bandit security scanning'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run Python security and type checks
      shell: bash
      env:
        SERVICE_PATH: ${{ inputs.service-path }}
        CHECK_TYPES: ${{ inputs.check-types }}
        CHECK_SECURITY: ${{ inputs.check-security }}
      run: ${{ github.action_path }}/script.sh
