name: 'Check Preview Pipeline Status'
description: 'Validates preview pipeline results and creates status summary'
inputs:
  needs-image-build:
    description: 'Whether PR needs image build (true/false)'
    required: true
  needs-deployment:
    description: 'Whether PR needs deployment (true/false)'
    required: true
  update-overlay-result:
    description: 'Result of update-overlay job'
    required: true
  verify-deployment-result:
    description: 'Result of verify-deployment job'
    required: true
  deploy-frontend-result:
    description: 'Result of deploy-frontend-preview job'
    required: true
  e2e-tests-result:
    description: 'Result of e2e-tests job'
    required: true
  api-url-configured:
    description: 'Whether API URL is configured'
    required: false
    default: ''
  wait-for-ci-result:
    description: 'Result of wait-for-ci job'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Check preview pipeline status
      shell: bash
      env:
        NEEDS_IMAGE_BUILD: ${{ inputs.needs-image-build }}
        NEEDS_DEPLOYMENT: ${{ inputs.needs-deployment }}
        UPDATE_OVERLAY_RESULT: ${{ inputs.update-overlay-result }}
        VERIFY_DEPLOYMENT_RESULT: ${{ inputs.verify-deployment-result }}
        DEPLOY_FRONTEND_RESULT: ${{ inputs.deploy-frontend-result }}
        E2E_TESTS_RESULT: ${{ inputs.e2e-tests-result }}
        API_URL_CONFIGURED: ${{ inputs.api-url-configured }}
        WAIT_FOR_CI_RESULT: ${{ inputs.wait-for-ci-result }}
      run: ${{ github.action_path }}/script.sh
