name: Validate Resource Quota
description: Validates that Kubernetes manifest resources are within quota limits

inputs:
  manifest-file:
    description: Path to the Kubernetes manifest file to validate
    required: true
  max-cpu:
    description: Maximum CPU requests in millicores (e.g., 1500 for 1.5 CPU)
    required: false
    default: ''
  max-memory:
    description: Maximum memory requests in Mi (e.g., 2048 for 2Gi)
    required: false
    default: ''
  resource-name:
    description: Name of the resource for error messages
    required: false
    default: 'resource'

runs:
  using: composite
  steps:
    - name: Validate resource quota
      shell: bash
      env:
        MANIFEST_FILE: ${{ inputs.manifest-file }}
        MAX_CPU: ${{ inputs.max-cpu }}
        MAX_MEMORY: ${{ inputs.max-memory }}
        RESOURCE_NAME: ${{ inputs.resource-name }}
      run: bash ${{ github.action_path }}/script.sh
