name: 'Check CI Job Results'
description: 'Checks all CI job results and reports pass/fail status'
inputs:
  test-shared-result:
    description: 'Result of test-shared job'
    required: true
  test-shared-should-run:
    description: 'Whether test-shared should have run'
    required: true
  test-api-result:
    description: 'Result of test-api job'
    required: true
  test-api-should-run:
    description: 'Whether test-api should have run'
    required: true
  test-workers-result:
    description: 'Result of test-workers job'
    required: true
  test-workers-should-run:
    description: 'Whether test-workers should have run'
    required: true
  test-frontend-result:
    description: 'Result of test-frontend job'
    required: true
  test-frontend-should-run:
    description: 'Whether test-frontend should have run'
    required: true
  lint-python-result:
    description: 'Result of lint-python job'
    required: true
  lint-python-should-run:
    description: 'Whether lint-python should have run'
    required: true
  lint-frontend-result:
    description: 'Result of lint-frontend job'
    required: true
  lint-frontend-should-run:
    description: 'Whether lint-frontend should have run'
    required: true
  build-images-validate-result:
    description: 'Result of build-images-validate job'
    required: true
  build-images-validate-should-run:
    description: 'Whether build-images-validate should have run'
    required: true
  validate-terraform-result:
    description: 'Result of validate-terraform job'
    required: true
  validate-terraform-should-run:
    description: 'Whether validate-terraform should have run'
    required: true
  validate-kustomize-result:
    description: 'Result of validate-kustomize job'
    required: true
  validate-kustomize-should-run:
    description: 'Whether validate-kustomize should have run'
    required: true
  kubernetes-validate-result:
    description: 'Result of kubernetes-validate job'
    required: true
  kubernetes-validate-should-run:
    description: 'Whether kubernetes-validate should have run'
    required: true
  secret-scanning-result:
    description: 'Result of secret-scanning job'
    required: true
  secret-scanning-should-run:
    description: 'Whether secret-scanning should have run'
    required: true
runs:
  using: composite
  steps:
    - name: Check all jobs passed
      shell: bash
      run: |
        # Helper to check if job passed or was appropriately skipped
        check_job() {
          local name=$1
          local result=$2
          local should_run=$3
          
          if [ "$should_run" = "true" ]; then
            if [ "$result" != "success" ]; then
              echo "❌ $name failed (result: $result)"
              return 1
            fi
            echo "✅ $name passed"
          else
            echo "⏭️  $name skipped (not required)"
          fi
          return 0
        }
        
        EXIT_CODE=0
        
        echo "Checking CI results..."
        echo ""
        
        # Check test jobs
        check_job "test-shared" "${{ inputs.test-shared-result }}" "${{ inputs.test-shared-should-run }}" || EXIT_CODE=1
        check_job "test-api" "${{ inputs.test-api-result }}" "${{ inputs.test-api-should-run }}" || EXIT_CODE=1
        check_job "test-workers" "${{ inputs.test-workers-result }}" "${{ inputs.test-workers-should-run }}" || EXIT_CODE=1
        check_job "test-frontend" "${{ inputs.test-frontend-result }}" "${{ inputs.test-frontend-should-run }}" || EXIT_CODE=1
        
        # Check lint jobs
        check_job "lint-python" "${{ inputs.lint-python-result }}" "${{ inputs.lint-python-should-run }}" || EXIT_CODE=1
        check_job "lint-frontend" "${{ inputs.lint-frontend-result }}" "${{ inputs.lint-frontend-should-run }}" || EXIT_CODE=1
        
        # Check build/validation jobs
        check_job "build-images-validate" "${{ inputs.build-images-validate-result }}" "${{ inputs.build-images-validate-should-run }}" || EXIT_CODE=1
        check_job "validate-terraform" "${{ inputs.validate-terraform-result }}" "${{ inputs.validate-terraform-should-run }}" || EXIT_CODE=1
        check_job "validate-kustomize" "${{ inputs.validate-kustomize-result }}" "${{ inputs.validate-kustomize-should-run }}" || EXIT_CODE=1
        check_job "kubernetes-validate" "${{ inputs.kubernetes-validate-result }}" "${{ inputs.kubernetes-validate-should-run }}" || EXIT_CODE=1
        check_job "secret-scanning" "${{ inputs.secret-scanning-result }}" "${{ inputs.secret-scanning-should-run }}" || EXIT_CODE=1
        
        echo ""
        if [ $EXIT_CODE -eq 0 ]; then
          echo "✅ All required CI checks passed"
        else
          echo "❌ Some CI checks failed"
        fi
        
        exit $EXIT_CODE
