name: 'Verify CI Workflow Passed'
description: 'Verifies that the CI workflow completed successfully (for workflow_run triggers)'
inputs:
  workflow-conclusion:
    description: 'Conclusion of the workflow run'
    required: true
  workflow-name:
    description: 'Name of the workflow that triggered this run'
    required: true
runs:
  using: composite
  steps:
    - name: Verify workflow passed
      shell: bash
      env:
        WORKFLOW_CONCLUSION: ${{ inputs.workflow-conclusion }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
      run: bash ${{ github.action_path }}/script.sh
