name: Verify Certificate
description: Verify TLS certificate is valid and not expired
# Renamed from: verify-tls-certificate (for naming consistency)

inputs:
  host:
    description: Hostname to verify
    required: true

runs:
  using: composite
  steps:
    - name: Verify certificate
      shell: bash
      run: ${{ github.action_path }}/verify-tls.sh "${{ inputs.host }}"
