name: Assert Image Tag Artifact
description: Verifies that the image-tag artifact was downloaded correctly

inputs:
  artifact_path:
    description: Path to the downloaded artifact file
    required: true
    default: './downloaded-artifacts/image-tag.txt'

runs:
  using: composite
  steps:
    - name: Assert downloaded image tag
      shell: bash
      env:
        ARTIFACT_PATH: ${{ inputs.artifact_path }}
      run: bash ${{ github.action_path }}/script.sh
