name: Get PR Metadata
description: Extracts PR number, head ref, and head SHA from pull_request or workflow_dispatch events

inputs:
  event-name:
    description: 'GitHub event name'
    required: true
  pr-number-input:
    description: 'PR number from workflow_dispatch input (optional)'
    required: false
    default: ''
  pr-number-context:
    description: 'PR number from pull_request context'
    required: false
    default: ''
  pr-head-ref-context:
    description: 'PR head ref from pull_request context'
    required: false
    default: ''
  pr-head-sha-context:
    description: 'PR head SHA from pull_request context'
    required: false
    default: ''
  pr-base-sha-context:
    description: 'PR base SHA from pull_request context'
    required: false
    default: ''
  current-ref:
    description: 'Current ref name'
    required: true
  current-sha:
    description: 'Current SHA'
    required: true

outputs:
  pr_number:
    description: 'PR number'
    value: ${{ steps.extract.outputs.pr_number }}
  pr_head_ref:
    description: 'PR head ref'
    value: ${{ steps.extract.outputs.pr_head_ref }}
  pr_head_sha:
    description: 'PR head SHA'
    value: ${{ steps.extract.outputs.pr_head_sha }}
  base_sha:
    description: 'Base SHA for comparison'
    value: ${{ steps.extract.outputs.base_sha }}

runs:
  using: composite
  steps:
    - name: Extract PR metadata
      id: extract
      shell: bash
      env:
        EVENT_NAME: ${{ inputs.event-name }}
        PR_NUMBER_INPUT: ${{ inputs.pr-number-input }}
        PR_NUMBER_CONTEXT: ${{ inputs.pr-number-context }}
        PR_HEAD_REF_CONTEXT: ${{ inputs.pr-head-ref-context }}
        PR_HEAD_SHA_CONTEXT: ${{ inputs.pr-head-sha-context }}
        PR_BASE_SHA_CONTEXT: ${{ inputs.pr-base-sha-context }}
        CURRENT_REF: ${{ inputs.current-ref }}
        CURRENT_SHA: ${{ inputs.current-sha }}
      run: ${{ github.action_path }}/get-pr-metadata.sh
