name: Validate Image Tag
description: Validates that the canonical image tag from CI matches the expected tag for a PR

inputs:
  ci-image-tag:
    description: 'Image tag extracted from CI artifact'
    required: true
    default: ''
  pr-number:
    description: 'Pull request number'
    required: false
    default: ''
  commit-sha:
    description: 'Commit SHA to use when computing expected tag'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Compute expected image tag
      id: compute
      uses: ./.github/actions/generate-image-tag
      with:
        pr-number: ${{ inputs.pr-number }}
        commit-sha: ${{ inputs.commit-sha }}

    - name: Compare tags and validate
      shell: bash
      env:
        CI_TAG: ${{ inputs.ci-image-tag }}
        EXPECTED_TAG: ${{ steps.compute.outputs.image-tag }}
      run: ${{ github.action_path }}/validate-image-tag.sh
