name: Find Stale PRs
description: Identifies closed PRs that may have stale SWA staging environments

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  min-age-hours:
    description: Minimum age in hours before a closed PR is considered stale
    required: false
    default: '1'
  max-prs-to-check:
    description: Maximum number of closed PRs to check
    required: false
    default: '100'

outputs:
  stale-prs:
    description: Comma-separated list of stale PR numbers
    value: ${{ steps.find.outputs.stale_prs }}
  stale-count:
    description: Number of stale PRs found
    value: ${{ steps.find.outputs.stale_count }}

runs:
  using: composite
  steps:
    - name: Find stale PRs
      id: find
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        MIN_AGE_HOURS: ${{ inputs.min-age-hours }}
        MAX_PRS: ${{ inputs.max-prs-to-check }}
      run: ${{ github.action_path }}/find-stale-prs.sh
