name: 'Validate CI Pipeline Results'
description: 'Checks all CI job results and validates pipeline completion'
inputs:
  changed-areas:
    description: 'Space-separated list of changed areas from detect-changes'
    required: true
  is-main-branch:
    description: 'Whether this is the main branch (full validation mode)'
    required: true
  # Test job results
  test-shared-result:
    description: 'Result of test-shared job'
    required: true
  test-api-result:
    description: 'Result of test-api job'
    required: true
  test-workers-result:
    description: 'Result of test-workers job'
    required: true
  frontend-quality-result:
    description: 'Result of frontend-quality job'
    required: true
  # Validation job results
  validate-terraform-result:
    description: 'Result of validate-terraform job'
    required: true
  kubernetes-validate-result:
    description: 'Result of kubernetes-validate job'
    required: true
  secret-scanning-result:
    description: 'Result of secret-scanning job'
    required: true
  secret-scanning-should-run:
    description: 'Whether secret-scanning should have run'
    required: true
  # Build job results
  build-images-result:
    description: 'Result of build-images job'
    required: true
  acr-configured:
    description: 'Whether ACR is configured (vars.ACR_NAME is set)'
    required: true

runs:
  using: composite
  steps:
    - name: Validate CI results
      shell: bash
      env:
        IS_MAIN_BRANCH: ${{ inputs.is-main-branch }}
        CHANGED_AREAS: ${{ inputs.changed-areas }}
        ACR_CONFIGURED: ${{ inputs.acr-configured }}
        TEST_SHARED_RESULT: ${{ inputs.test-shared-result }}
        TEST_API_RESULT: ${{ inputs.test-api-result }}
        TEST_WORKERS_RESULT: ${{ inputs.test-workers-result }}
        FRONTEND_QUALITY_RESULT: ${{ inputs.frontend-quality-result }}
        VALIDATE_TERRAFORM_RESULT: ${{ inputs.validate-terraform-result }}
        KUBERNETES_VALIDATE_RESULT: ${{ inputs.kubernetes-validate-result }}
        SECRET_SCANNING_RESULT: ${{ inputs.secret-scanning-result }}
        SECRET_SCANNING_SHOULD_RUN: ${{ inputs.secret-scanning-should-run }}
        BUILD_IMAGES_RESULT: ${{ inputs.build-images-result }}
      run: bash ${{ github.action_path }}/script.sh
