name: 'Validate CI Pipeline Results'
description: 'Checks all CI job results and validates pipeline completion'
inputs:
  # Test job results
  test-shared-result:
    description: 'Result of test-shared job'
    required: true
  test-shared-should-run:
    description: 'Whether test-shared should have run'
    required: true
  test-api-result:
    description: 'Result of test-api job'
    required: true
  test-api-should-run:
    description: 'Whether test-api should have run'
    required: true
  test-workers-result:
    description: 'Result of test-workers job'
    required: true
  test-workers-should-run:
    description: 'Whether test-workers should have run'
    required: true
  test-frontend-result:
    description: 'Result of test-frontend job'
    required: true
  test-frontend-should-run:
    description: 'Whether test-frontend should have run'
    required: true
  # Validation job results
  validate-terraform-result:
    description: 'Result of validate-terraform job'
    required: true
  validate-terraform-should-run:
    description: 'Whether validate-terraform should have run'
    required: true
  validate-kustomize-result:
    description: 'Result of validate-kustomize job'
    required: true
  kubernetes-validate-result:
    description: 'Result of kubernetes-validate job'
    required: true
  kubernetes-validate-should-run:
    description: 'Whether kubernetes-validate should have run'
    required: true
  secret-scanning-result:
    description: 'Result of secret-scanning job'
    required: true
  secret-scanning-should-run:
    description: 'Whether secret-scanning should have run'
    required: true
  # Build job results
  build-images-result:
    description: 'Result of build-images job'
    required: true
  build-images-validate-result:
    description: 'Result of build-images-validate job'
    required: true
  build-images-should-run:
    description: 'Whether build jobs should have run'
    required: true
runs:
  using: composite
  steps:
    - name: Validate CI results
      shell: bash
      run: |
        # Helper to check if job passed or was appropriately skipped
        check_job() {
          local name=$1
          local result=$2
          local should_run=$3
          
          if [ "$should_run" = "true" ]; then
            if [ "$result" != "success" ]; then
              echo "❌ $name failed (result: $result)"
              return 1
            fi
            echo "✅ $name passed"
          else
            echo "⏭️  $name skipped (not required)"
          fi
          return 0
        }
        
        EXIT_CODE=0
        
        echo "Checking CI results..."
        echo ""
        
        # Check test jobs
        check_job "test-shared" "${{ inputs.test-shared-result }}" "${{ inputs.test-shared-should-run }}" || EXIT_CODE=1
        check_job "test-api" "${{ inputs.test-api-result }}" "${{ inputs.test-api-should-run }}" || EXIT_CODE=1
        check_job "test-workers" "${{ inputs.test-workers-result }}" "${{ inputs.test-workers-should-run }}" || EXIT_CODE=1
        check_job "test-frontend" "${{ inputs.test-frontend-result }}" "${{ inputs.test-frontend-should-run }}" || EXIT_CODE=1
        
        # Check validation jobs
        check_job "validate-terraform" "${{ inputs.validate-terraform-result }}" "${{ inputs.validate-terraform-should-run }}" || EXIT_CODE=1
        check_job "kubernetes-validate" "${{ inputs.kubernetes-validate-result }}" "${{ inputs.kubernetes-validate-should-run }}" || EXIT_CODE=1
        check_job "secret-scanning" "${{ inputs.secret-scanning-result }}" "${{ inputs.secret-scanning-should-run }}" || EXIT_CODE=1
        
        # Check validate-kustomize (always required if it ran)
        if [ "${{ inputs.validate-kustomize-result }}" != "success" ] && [ "${{ inputs.validate-kustomize-result }}" != "skipped" ]; then
          echo "❌ validate-kustomize failed"
          EXIT_CODE=1
        else
          echo "✅ validate-kustomize passed"
        fi
        
        # Check build jobs - one must succeed if builds are required
        if [ "${{ inputs.build-images-should-run }}" = "true" ]; then
          BUILD_PUSH="${{ inputs.build-images-result }}"
          BUILD_VALIDATE="${{ inputs.build-images-validate-result }}"
          
          if [ "$BUILD_PUSH" = "success" ] || [ "$BUILD_PUSH" = "skipped" -a "$BUILD_VALIDATE" = "success" ]; then
            echo "✅ Build validation passed"
          else
            echo "❌ Build jobs failed: build-images=$BUILD_PUSH, build-images-validate=$BUILD_VALIDATE"
            EXIT_CODE=1
          fi
        else
          echo "⏭️  Build jobs skipped (no changes requiring image builds)"
        fi
        
        echo ""
        if [ $EXIT_CODE -eq 0 ]; then
          echo "🎉 All CI checks passed!"
        else
          echo "💥 One or more CI checks failed"
        fi
        
        exit $EXIT_CODE
