name: 'Validate CI Pipeline Results'
description: 'Checks all CI job results and validates pipeline completion'
inputs:
  changed-areas:
    description: 'Space-separated list of changed areas from detect-changes'
    required: true
  # Test job results
  test-shared-result:
    description: 'Result of test-shared job'
    required: true
  test-api-result:
    description: 'Result of test-api job'
    required: true
  test-workers-result:
    description: 'Result of test-workers job'
    required: true
  test-frontend-result:
    description: 'Result of test-frontend job'
    required: true
  # Validation job results
  validate-terraform-result:
    description: 'Result of validate-terraform job'
    required: true
  validate-kustomize-result:
    description: 'Result of validate-kustomize job'
    required: true
  kubernetes-validate-result:
    description: 'Result of kubernetes-validate job'
    required: true
  secret-scanning-result:
    description: 'Result of secret-scanning job'
    required: true
  secret-scanning-should-run:
    description: 'Whether secret-scanning should have run'
    required: true
  # Build job results
  build-images-result:
    description: 'Result of build-images job'
    required: true
  build-images-validate-result:
    description: 'Result of build-images-validate job'
    required: true
  acr-configured:
    description: 'Whether ACR is configured (vars.ACR_NAME is set)'
    required: true

runs:
  using: composite
  steps:
    - name: Validate CI results
      shell: bash
      run: |
        # =====================================================================
        # DESIGN DECISION: Replicate job logic here for validation
        # =====================================================================
        # This action checks if jobs passed OR were correctly skipped.
        # It replicates the same changed_areas logic as job conditions.
        #
        # WHY?
        # - Validates that the pipeline executed correctly
        # - Ensures jobs didn't run when they shouldn't (waste CI time)
        # - Ensures jobs DID run when they should (catch missing tests)
        #
        # MAINTENANCE: When adding a new job to ci.yml, add its logic here
        # Example: if you add "test-new-service" with condition
        #   contains(changed_areas, 'services/new')
        # Then add a case in should_run_job() for "test-new-service"
        # =====================================================================
        
        # Helper to check if job should have run based on changed areas
        should_run_job() {
          local areas="${{ inputs.changed-areas }}"
          case "$1" in
            "test-shared")
              [[ "$areas" =~ services/shared ]]
              ;;
            "test-api")
              [[ "$areas" =~ services/api ]] || [[ "$areas" =~ services/shared ]]
              ;;
            "test-workers")
              [[ "$areas" =~ services/workers ]] || [[ "$areas" =~ services/shared ]]
              ;;
            "test-frontend")
              [[ "$areas" =~ apps/web ]]
              ;;
            "validate-terraform")
              [[ "$areas" =~ infra/terraform ]]
              ;;
            "kubernetes-validate")
              [[ "$areas" =~ k8s ]]
              ;;
            "build-images")
              # Must have ACR configured AND changes to buildable areas
              [[ "${{ inputs.acr-configured }}" == "true" ]] && \
              ([[ "$areas" =~ services/api ]] || [[ "$areas" =~ services/workers ]] || [[ "$areas" =~ services/shared ]] || [[ "$areas" =~ apps/web ]] || [[ "$areas" =~ docker ]] || [[ "$areas" =~ k8s ]])
              ;;
            *)
              return 1
              ;;
          esac
        }
        
        # Helper to check if job passed or was appropriately skipped
        check_job() {
          local name=$1
          local result=$2
          
          if should_run_job "$name"; then
            if [ "$result" != "success" ]; then
              echo "❌ $name failed (result: $result)"
              return 1
            fi
            echo "✅ $name passed"
          else
            echo "⏭️  $name skipped (not required)"
          fi
          return 0
        }
        
        EXIT_CODE=0
        
        echo "Checking CI results..."
        echo ""
        
        # Check test jobs
        check_job "test-shared" "${{ inputs.test-shared-result }}" || EXIT_CODE=1
        check_job "test-api" "${{ inputs.test-api-result }}" || EXIT_CODE=1
        check_job "test-workers" "${{ inputs.test-workers-result }}" || EXIT_CODE=1
        check_job "test-frontend" "${{ inputs.test-frontend-result }}" || EXIT_CODE=1
        
        # Check validation jobs
        check_job "validate-terraform" "${{ inputs.validate-terraform-result }}" || EXIT_CODE=1
        check_job "kubernetes-validate" "${{ inputs.kubernetes-validate-result }}" || EXIT_CODE=1
        check_job "secret-scanning" "${{ inputs.secret-scanning-result }}" "${{ inputs.secret-scanning-should-run }}" || EXIT_CODE=1
        
        # Check validate-kustomize (always required if it ran)
        if [ "${{ inputs.validate-kustomize-result }}" != "success" ] && [ "${{ inputs.validate-kustomize-result }}" != "skipped" ]; then
          echo "❌ validate-kustomize failed"
          EXIT_CODE=1
        else
          echo "✅ validate-kustomize passed"
        fi
        
        # Check build jobs - one must succeed if builds are required
        if should_run_job "build-images"; then
          BUILD_PUSH="${{ inputs.build-images-result }}"
          BUILD_VALIDATE="${{ inputs.build-images-validate-result }}"
          
          if [ "$BUILD_PUSH" = "success" ] || [ "$BUILD_PUSH" = "skipped" -a "$BUILD_VALIDATE" = "success" ]; then
            echo "✅ Build validation passed"
          else
            echo "❌ Build jobs failed: build-images=$BUILD_PUSH, build-images-validate=$BUILD_VALIDATE"
            EXIT_CODE=1
          fi
        else
          echo "⏭️  Build jobs skipped (no changes requiring image builds)"
        fi
        
        echo ""
        if [ $EXIT_CODE -eq 0 ]; then
          echo "🎉 All CI checks passed!"
        else
          echo "💥 One or more CI checks failed"
        fi
        
        exit $EXIT_CODE
