name: Get Production Image Tag
description: Extracts the current image tag from the production Kustomize overlay

inputs:
  overlay-path:
    description: 'Path to the production overlay kustomization.yaml'
    required: false
    default: 'k8s/overlays/prod/kustomization.yaml'

outputs:
  image_tag:
    description: 'Current production image tag'
    value: ${{ steps.extract.outputs.image_tag }}

runs:
  using: composite
  steps:
    - name: Extract production image tag
      id: extract
      shell: bash
      run: |
        OVERLAY_PATH="${{ inputs.overlay-path }}"
        
        if [ ! -f "$OVERLAY_PATH" ]; then
          echo "::error::Production overlay not found at: $OVERLAY_PATH"
          exit 1
        fi
        
        IMAGE_TAG=$(grep -oP 'newTag: \K.*' "$OVERLAY_PATH" | head -1)
        
        if [ -z "$IMAGE_TAG" ]; then
          echo "::error::Could not find image tag (newTag) in production overlay"
          exit 1
        fi
        
        echo "Found production image tag: $IMAGE_TAG"
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
