name: Get Production Image Tag
description: Extracts the current image tag from the production Kustomize overlay

inputs:
  overlay-path:
    description: 'Path to the production overlay kustomization.yaml'
    required: false
    default: 'k8s/overlays/prod/kustomization.yaml'

outputs:
  image_tag:
    description: 'Current production image tag'
    value: ${{ steps.extract.outputs.image_tag }}

runs:
  using: composite
  steps:
    - name: Extract production image tag
      id: extract
      shell: bash
      env:
        OVERLAY_PATH: ${{ inputs.overlay-path }}
      run: bash ${{ github.action_path }}/script.sh
