# Reusable health check action
# Polls an endpoint until it returns healthy or times out

name: 'Health Check'
description: 'Wait for service to become healthy'

inputs:
  url:
    description: 'Health check URL (e.g., https://api.example.com/health/live)'
    required: true
  max-attempts:
    description: 'Maximum number of attempts'
    required: false
    default: '30'
  interval-seconds:
    description: 'Seconds between attempts'
    required: false
    default: '10'
  timeout-seconds:
    description: 'Timeout for each request in seconds'
    required: false
    default: '5'
  expected-status:
    description: 'Expected HTTP status code'
    required: false
    default: '200'
  service-name:
    description: 'Service name for logging'
    required: false
    default: 'Service'

outputs:
  healthy:
    description: 'Whether the service became healthy'
    value: ${{ steps.check.outputs.healthy }}
  attempts:
    description: 'Number of attempts made'
    value: ${{ steps.check.outputs.attempts }}

runs:
  using: 'composite'
  steps:
    - name: Wait for service health
      id: check
      shell: bash
      env:
        URL: ${{ inputs.url }}
        MAX_ATTEMPTS: ${{ inputs.max-attempts }}
        INTERVAL: ${{ inputs.interval-seconds }}
        TIMEOUT: ${{ inputs.timeout-seconds }}
        EXPECTED_STATUS: ${{ inputs.expected-status }}
        SERVICE_NAME: ${{ inputs.service-name }}
      run: ${{ github.action_path }}/health-check.sh
