name: 'Create Pipeline Summary'
description: 'Creates GitHub step summary for CI/Preview/Prod/Cleanup pipelines'

inputs:
  summary-type:
    description: 'Type of summary: ci|preview|prod|cleanup'
    required: true

  # Common inputs (all types)
  commit-sha:
    description: 'Git commit SHA'
    required: false
  repository:
    description: 'GitHub repository (owner/repo)'
    required: false
  run-id:
    description: 'GitHub Actions run ID'
    required: false

  # CI-specific inputs
  changed-areas:
    description: 'CI: Space-separated list of changed areas'
    required: false
  pr-number:
    description: 'CI/Preview/Cleanup: Pull request number'
    required: false
  lint-python-result:
    description: 'CI: Result of lint-python job'
    required: false
    default: 'skipped'
  frontend-quality-result:
    description: 'CI: Result of frontend-quality job'
    required: false
    default: 'skipped'
  scan-python-security-result:
    description: 'CI: Result of scan-python-security job'
    required: false
    default: 'skipped'
  secret-scanning-result:
    description: 'CI: Result of secret-scanning job'
    required: false
    default: 'skipped'
  test-shared-result:
    description: 'CI: Result of test-shared job'
    required: false
    default: 'skipped'
  test-shared-duration:
    description: 'CI: Duration of test-shared job'
    required: false
  test-api-result:
    description: 'CI: Result of test-api job'
    required: false
    default: 'skipped'
  test-api-duration:
    description: 'CI: Duration of test-api job'
    required: false
  test-workers-result:
    description: 'CI: Result of test-workers job'
    required: false
    default: 'skipped'
  test-workers-duration:
    description: 'CI: Duration of test-workers job'
    required: false
  kubernetes-validate-result:
    description: 'CI: Result of kubernetes-validate job'
    required: false
    default: 'skipped'
  validate-kustomize-result:
    description: 'CI: Result of validate-kustomize job'
    required: false
    default: 'skipped'
  validate-terraform-result:
    description: 'CI: Result of validate-terraform job'
    required: false
    default: 'skipped'
  build-images-result:
    description: 'CI: Result of build-images job'
    required: false
    default: 'skipped'
  image-tag:
    description: 'CI/Preview/Prod: Docker image tag'
    required: false

  # Preview-specific inputs
  preview-url:
    description: 'Preview: Preview environment URL'
    required: false

  # Production-specific inputs
  update-overlay-result:
    description: 'Prod: Result of update-overlay job'
    required: false
  deploy-frontend-result:
    description: 'Prod: Result of deploy-frontend job'
    required: false
  verify-deployment-result:
    description: 'Prod: Result of verify-deployment job'
    required: false

  # Cleanup-specific inputs
  pr-merged:
    description: 'Cleanup: Whether the PR was merged (true/false)'
    required: false

runs:
  using: composite
  steps:
    - name: Generate pipeline summary
      shell: bash
      env:
        SUMMARY_TYPE: ${{ inputs.summary-type }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        REPOSITORY: ${{ inputs.repository }}
        RUN_ID: ${{ inputs.run-id }}
        # CI inputs
        CHANGED_AREAS: ${{ inputs.changed-areas }}
        PR_NUMBER: ${{ inputs.pr-number }}
        LINT_PYTHON_RESULT: ${{ inputs.lint-python-result }}
        FRONTEND_QUALITY_RESULT: ${{ inputs.frontend-quality-result }}
        SCAN_PYTHON_SECURITY_RESULT: ${{ inputs.scan-python-security-result }}
        SECRET_SCANNING_RESULT: ${{ inputs.secret-scanning-result }}
        TEST_SHARED_RESULT: ${{ inputs.test-shared-result }}
        TEST_SHARED_DURATION: ${{ inputs.test-shared-duration }}
        TEST_API_RESULT: ${{ inputs.test-api-result }}
        TEST_API_DURATION: ${{ inputs.test-api-duration }}
        TEST_WORKERS_RESULT: ${{ inputs.test-workers-result }}
        TEST_WORKERS_DURATION: ${{ inputs.test-workers-duration }}
        KUBERNETES_VALIDATE_RESULT: ${{ inputs.kubernetes-validate-result }}
        VALIDATE_KUSTOMIZE_RESULT: ${{ inputs.validate-kustomize-result }}
        VALIDATE_TERRAFORM_RESULT: ${{ inputs.validate-terraform-result }}
        BUILD_IMAGES_RESULT: ${{ inputs.build-images-result }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        # Preview inputs
        PREVIEW_URL: ${{ inputs.preview-url }}
        # Production inputs
        UPDATE_OVERLAY_RESULT: ${{ inputs.update-overlay-result }}
        DEPLOY_FRONTEND_RESULT: ${{ inputs.deploy-frontend-result }}
        VERIFY_DEPLOYMENT_RESULT: ${{ inputs.verify-deployment-result }}
        # Cleanup inputs
        PR_MERGED: ${{ inputs.pr-merged }}
      run: |
        case "$SUMMARY_TYPE" in
          ci)
            bash "${{ github.action_path }}/generate-ci-summary.sh"
            ;;
          preview)
            bash "${{ github.action_path }}/generate-preview-summary.sh"
            ;;
          prod)
            bash "${{ github.action_path }}/generate-prod-summary.sh"
            ;;
          cleanup)
            bash "${{ github.action_path }}/generate-cleanup-summary.sh"
            ;;
          *)
            echo "::error::Invalid summary-type: $SUMMARY_TYPE. Must be ci|preview|prod|cleanup"
            exit 1
            ;;
        esac
