name: 'Post Terraform Plan'
description: 'Posts Terraform plan to PR comments and generates pipeline summary'
inputs:
  plan-summary:
    description: 'JSON summary of plan changes (add, change, destroy, has_changes)'
    required: true
  formatted-plan:
    description: 'Formatted terraform plan output'
    required: true
  plan-outcome:
    description: 'Plan outcome (success/failure)'
    required: true
  skip-pr-comment:
    description: 'Skip posting to PR comment (true/false)'
    required: false
    default: 'false'
outputs:
  comment-id:
    description: 'ID of the created or updated PR comment'
    value: ${{ steps.post-pr.outputs.comment-id }}
runs:
  using: composite
  steps:
    - name: Generate plan section
      id: generate-sections
      shell: bash
      run: |
        # Parse inputs
        PLAN_SUMMARY='${{ inputs.plan-summary }}'
        FORMATTED_PLAN='${{ inputs.formatted-plan }}'
        PLAN_OUTCOME='${{ inputs.plan-outcome }}'

        # Write to output file for later steps
        echo "$PLAN_SUMMARY" > ${{ github.action_path }}/plan-summary.json
        echo "$FORMATTED_PLAN" > ${{ github.action_path }}/formatted-plan.txt
        echo "$PLAN_OUTCOME" > ${{ github.action_path }}/plan-outcome.txt

    - name: Post to PR
      id: post-pr
      if: ${{ inputs.skip-pr-comment != 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      env:
        PLAN_SUMMARY: ${{ inputs.plan-summary }}
        FORMATTED_PLAN: ${{ inputs.formatted-plan }}
        PLAN_OUTCOME: ${{ inputs.plan-outcome }}
      with:
        github-token: ${{ github.token }}
        retries: 3
        script: |
          const summary = JSON.parse(process.env.PLAN_SUMMARY || '{"add":0,"change":0,"destroy":0,"has_changes":false}');
          const rawPlan = process.env.FORMATTED_PLAN || 'No plan output available';
          const planOutcome = process.env.PLAN_OUTCOME;

          core.info(`🔍 Plan Outcome: ${planOutcome}`);
          core.info(`📊 Summary: Add=${summary.add}, Change=${summary.change}, Destroy=${summary.destroy}`);

          const statusEmoji = planOutcome === 'success' ? '✅' : '❌';
          const statusText = planOutcome === 'success' ? 'Plan finished' : 'Plan failed';
          const hasChanges = summary.has_changes;

          // Parse resources from terraform plan output
          function parseResources(planOutput) {
            const resources = [];
            const lines = planOutput.split('\n');
            let currentResource = null;
            let currentDetails = [];
            let inResource = false;

            for (const line of lines) {
              // Match "# resource.name will be created/updated/destroyed"
              const resourceMatch = line.match(/^\s*#\s+(.+?)\s+(will be|must be)\s+(created|updated in-place|replaced|destroyed)/);
              if (resourceMatch) {
                if (currentResource) {
                  resources.push({ ...currentResource, details: currentDetails.join('\n') });
                }
                const actionText = resourceMatch[3];
                let action = 'read';
                if (actionText === 'created') action = 'create';
                else if (actionText === 'updated in-place') action = 'update';
                else if (actionText === 'replaced') action = 'replace';
                else if (actionText === 'destroyed') action = 'destroy';
                currentResource = { address: resourceMatch[1], action };
                currentDetails = [];
                inResource = true;
                continue;
              }

              if (inResource && line.trim()) {
                if (line.match(/^Plan:|^Changes to Outputs:|^Warning:|^─+$/)) {
                  inResource = false;
                  if (currentResource) {
                    resources.push({ ...currentResource, details: currentDetails.join('\n') });
                    currentResource = null;
                    currentDetails = [];
                  }
                } else {
                  currentDetails.push(line);
                }
              }
            }
            if (currentResource) {
              resources.push({ ...currentResource, details: currentDetails.join('\n') });
            }
            return resources;
          }

          const resources = parseResources(rawPlan);
          core.info(`📦 Parsed ${resources.length} resources from plan`);

          const creates = resources.filter(r => r.action === 'create');
          const updates = resources.filter(r => r.action === 'update');
          const replaces = resources.filter(r => r.action === 'replace');
          const destroys = resources.filter(r => r.action === 'destroy');

          function getActionIcon(action) {
            const icons = { create: '➕', update: '🔄', replace: '♻️', destroy: '🗑️' };
            return icons[action] || '📖';
          }

          function getActionBadge(action) {
            const badges = {
              create: '<span style="background:#10b981; color:white; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600;">+ create</span>',
              update: '<span style="background:#f59e0b; color:white; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600;">~ update</span>',
              replace: '<span style="background:#8b5cf6; color:white; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600;">-/+ replace</span>',
              destroy: '<span style="background:#ef4444; color:white; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600;">- destroy</span>'
            };
            return badges[action] || '<span style="background:#6b7280; color:white; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600;">read</span>';
          }

          function buildResourceSection(resource) {
            const icon = getActionIcon(resource.action);
            const badge = getActionBadge(resource.action);
            const cleanDetails = resource.details.split('\n').filter(l => l.trim()).map(l => l.replace(/^\s{4}/, '')).join('\n');
            return `<details>\n<summary>${icon} <span style="font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:13px; background:#f6f8fa; padding:2px 6px; border-radius:4px;">${resource.address}</span> ${badge}</summary>\n\n\`\`\`hcl\n${cleanDetails || '(no details)'}\n\`\`\`\n\n</details>`;
          }

          // Build summary badges like Terraform Cloud
          const summaryBadges = [];
          if (summary.add > 0) summaryBadges.push(
            `<span style="display:inline-flex;align-items:center;gap:6px;padding:6px 12px;background:#d1fae5;color:#065f46;border-radius:6px;font-weight:600;font-size:14px;">` +
            `<span style="font-size:18px;">⊕</span> <span>${summary.add}</span> <span style="font-weight:400;color:#047857;">to add</span></span>`
          );
          if (summary.change > 0) summaryBadges.push(
            `<span style="display:inline-flex;align-items:center;gap:6px;padding:6px 12px;background:#fef3c7;color:#92400e;border-radius:6px;font-weight:600;font-size:14px;">` +
            `<span style="font-size:18px;">≈</span> <span>${summary.change}</span> <span style="font-weight:400;color:#b45309;">to change</span></span>`
          );
          if (summary.destroy > 0) summaryBadges.push(
            `<span style="display:inline-flex;align-items:center;gap:6px;padding:6px 12px;background:#fee2e2;color:#991b1b;border-radius:6px;font-weight:600;font-size:14px;">` +
            `<span style="font-size:18px;">⊖</span> <span>${summary.destroy}</span> <span style="font-weight:400;color:#dc2626;">to destroy</span></span>`
          );

          const sections = [];
          sections.push(`<div style="margin-bottom:24px;">`);
          sections.push(`### ${statusEmoji} ${statusText}`);
          sections.push(`</div>`);
          sections.push('');

          // Footer - moved higher for visibility
          sections.push(`<div style="padding:12px 16px;background:#f8f9fa;border-left:4px solid:#0366d6;border-radius:0 6px 6px 0;margin-bottom:20px;">`);
          sections.push(`<div style="display:flex;flex-wrap:wrap;gap:16px;align-items:center;font-size:13px;color:#586069;line-height:1.6;">`);
          sections.push(`<div style="display:flex;align-items:center;gap:6px;">🕐 <strong>Last Updated:</strong> <code style="background:#e1e4e8;padding:2px 6px;border-radius:3px;font-size:12px;">${new Date().toISOString()}</code></div>`);
          sections.push(`<div style="display:flex;align-items:center;gap:6px;">👤 <strong>Triggered by:</strong> <span style="color:#0366d6;font-weight:500;">@${context.actor}</span></div>`);
          sections.push(`<div style="display:flex;align-items:center;gap:6px;">🔗 <a href="${context.payload.repository.html_url}/actions/runs/${context.runId}" style="color:#0366d6;text-decoration:none;font-weight:500;">View Workflow Run →</a></div>`);
          sections.push(`</div>`);
          sections.push(`</div>`);
          sections.push('');

          // Summary badges section
          if (hasChanges && summaryBadges.length > 0) {
            sections.push(`<div style="margin-bottom:20px;">`);
            sections.push(`#### Resource Changes`);
            sections.push('');
            sections.push(`<div style="display:flex;flex-wrap:wrap;gap:12px;align-items:center;">`);
            sections.push(...summaryBadges);
            sections.push(`</div>`);
            sections.push(`</div>`);
            sections.push('');
          } else if (!hasChanges) {
            sections.push(`<div style="padding:16px;background:#dcfce7;border:1px solid #86efac;border-radius:8px;margin-bottom:20px;">`);
            sections.push(`<div style="display:flex;align-items:center;gap:10px;color:#166534;font-size:15px;font-weight:500;">✅ No Changes</div>`);
            sections.push(`<div style="margin-top:6px;color:#15803d;font-size:14px;">Infrastructure matches configuration.</div>`);
            sections.push(`</div>`);
            sections.push('');
          }

          sections.push('<hr style="border:none;border-top:1px solid #e1e4e8;margin:24px 0;">');
          sections.push('');

          // Group by action type with expandable sections
          if (creates.length > 0) {
            sections.push(`<div style="margin-bottom:24px;">`);
            sections.push(`### <span style="color:#15803d;">➕</span> Resources to Create <span style="background:#d1fae5;color:#065f46;padding:2px 8px;border-radius:12px;font-size:12px;font-weight:600;">${creates.length}</span>`);
            sections.push('');
            creates.forEach(r => sections.push(buildResourceSection(r)));
            sections.push(`</div>`);
          }
          if (replaces.length > 0) {
            sections.push(`<div style="margin-bottom:24px;">`);
            sections.push(`### <span style="color:#7c3aed;">♻️</span> Resources to Replace <span style="background:#ede9fe;color:#5b21b6;padding:2px 8px;border-radius:12px;font-size:12px;font-weight:600;">${replaces.length}</span>`);
            sections.push('');
            replaces.forEach(r => sections.push(buildResourceSection(r)));
            sections.push(`</div>`);
          }
          if (updates.length > 0) {
            sections.push(`<div style="margin-bottom:24px;">`);
            sections.push(`### <span style="color:#b45309;">🔄</span> Resources to Update <span style="background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:12px;font-size:12px;font-weight:600;">${updates.length}</span>`);
            sections.push('');
            updates.forEach(r => sections.push(buildResourceSection(r)));
            sections.push(`</div>`);
          }
          if (destroys.length > 0) {
            sections.push(`<div style="margin-bottom:24px;">`);
            sections.push(`### <span style="color:#dc2626;">🗑️</span> Resources to Destroy <span style="background:#fee2e2;color:#991b1b;padding:2px 8px;border-radius:12px;font-size:12px;font-weight:600;">${destroys.length}</span>`);
            sections.push('');
            destroys.forEach(r => sections.push(buildResourceSection(r)));
            sections.push(`</div>`);
          }

          // Fallback: show raw plan if no resources parsed
          if (resources.length === 0 && hasChanges) {
            sections.push('<details>');
            sections.push('<summary style="cursor:pointer;padding:12px;background:#f6f8fa;border:1px solid #d1d5da;border-radius:6px;font-size:14px;font-weight:600;color:#24292f;"><b>📋 View Raw Plan Output</b></summary>');
            sections.push('');
            sections.push('```hcl');
            sections.push(rawPlan.length > 60000 ? rawPlan.substring(0, 60000) + '\n...(truncated)' : rawPlan);
            sections.push('```');
            sections.push('</details>');
            sections.push('');
          }

          const commentBody = sections.join('\n');

          core.info('📝 Fetching comments...');
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            per_page: 100
          });

          const botComment = comments.find(c => c.user.type === 'Bot' && (c.body.includes('Plan finished') || c.body.includes('Plan failed') || c.body.includes('Terraform Plan')));
          core.info(`🔍 Found ${comments.length} comments, ${botComment ? 'updating existing' : 'creating new'}`);

          let commentId = null;
          try {
            if (botComment) {
              core.info(`📝 Updating comment ${botComment.id}...`);
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
              core.info(`✅ Comment updated`);
              commentId = botComment.id;
            } else {
              core.info(`📝 Creating comment...`);
              const result = await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
              core.info(`✅ Comment created: ${result.data.id}`);
              commentId = result.data.id;
            }
            core.notice(`🎉 Terraform plan posted to PR #${context.issue.number}`);
          } catch (error) {
            core.error(`❌ Failed: ${error.message}`);
            core.setFailed(error.stack);
            throw error;
          }

          core.setOutput('comment-id', commentId);

    - name: Update pipeline summary
      shell: bash
      run: |
        PLAN_SUMMARY='${{ inputs.plan-summary }}'
        FORMATTED_PLAN='${{ inputs.formatted-plan }}'
        PLAN_OUTCOME='${{ inputs.plan-outcome }}'

        # Parse summary from JSON (using simple string parsing)
        ADD=$(echo "$PLAN_SUMMARY" | grep -o '"add":[0-9]*' | cut -d':' -f2)
        CHANGE=$(echo "$PLAN_SUMMARY" | grep -o '"change":[0-9]*' | cut -d':' -f2)
        DESTROY=$(echo "$PLAN_SUMMARY" | grep -o '"destroy":[0-9]*' | cut -d':' -f2)
        HAS_CHANGES=$(echo "$PLAN_SUMMARY" | grep -o '"has_changes":[^,}]*' | cut -d':' -f2)

        if [ "$PLAN_OUTCOME" = "success" ]; then
          echo "## ✅ Terraform Plan - Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '<div style="padding:12px 16px;background:#dcfce7;border:1px solid #86efac;border-radius:8px;margin-top:12px;">' >> $GITHUB_STEP_SUMMARY
          echo '<span style="color:#166534;font-size:14px;font-weight:500;">Infrastructure changes validated successfully</span>' >> $GITHUB_STEP_SUMMARY
          echo '</div>' >> $GITHUB_STEP_SUMMARY
        else
          echo "## ❌ Terraform Plan - Failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '<div style="padding:12px 16px;background:#fee2e2;border:1px solid #fca5a5;border-radius:8px;margin-top:12px;">' >> $GITHUB_STEP_SUMMARY
          echo '<span style="color:#991b1b;font-size:14px;font-weight:500;">Terraform plan encountered errors</span>' >> $GITHUB_STEP_SUMMARY
          echo '</div>' >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ "$HAS_CHANGES" = "true" ]; then
          echo "### 📊 Resource Changes" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '<div style="display:flex;flex-wrap:wrap;gap:12px;margin-top:12px;">' >> $GITHUB_STEP_SUMMARY

          if [ "$ADD" -gt 0 ]; then
            echo '<span style="display:inline-flex;align-items:center;gap:6px;padding:8px 12px;background:#d1fae5;color:#065f46;border-radius:6px;font-weight:600;">⊕ <span>'"${ADD}"'</span> <span style="font-weight:400;color:#047857;">to add</span></span>' >> $GITHUB_STEP_SUMMARY
          fi
          if [ "$CHANGE" -gt 0 ]; then
            echo '<span style="display:inline-flex;align-items:center;gap:6px;padding:8px 12px;background:#fef3c7;color:#92400e;border-radius:6px;font-weight:600;">≈ <span>'"${CHANGE}"'</span> <span style="font-weight:400;color:#b45309;">to change</span></span>' >> $GITHUB_STEP_SUMMARY
          fi
          if [ "$DESTROY" -gt 0 ]; then
            echo '<span style="display:inline-flex;align-items:center;gap:6px;padding:8px 12px;background:#fee2e2;color:#991b1b;border-radius:6px;font-weight:600;">⊖ <span>'"${DESTROY}"'</span> <span style="font-weight:400;color:#dc2626;">to destroy</span></span>' >> $GITHUB_STEP_SUMMARY
          fi

          echo '</div>' >> $GITHUB_STEP_SUMMARY
        else
          echo '<div style="padding:16px;background:#dcfce7;border:1px solid #86efac;border-radius:8px;margin-top:12px;margin-bottom:12px;">' >> $GITHUB_STEP_SUMMARY
          echo '<div style="display:flex;align-items:center;gap:10px;color:#166534;font-size:15px;font-weight:500;">✅ No Changes Detected</div>' >> $GITHUB_STEP_SUMMARY
          echo '<div style="margin-top:6px;color:#15803d;font-size:14px;">Infrastructure matches configuration. No deployment required.</div>' >> $GITHUB_STEP_SUMMARY
          echo '</div>' >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Store outputs
      id: outputs
      shell: bash
      run: |
        # Store comment-id if available (from PR post step)
        if [ -n "${{ steps.post-pr.outputs.comment-id }}" ]; then
          echo "comment-id=${{ steps.post-pr.outputs.comment-id }}" >> $GITHUB_OUTPUT
        fi
