name: 'Post Terraform Plan'
description: 'Posts Terraform plan to PR comments and generates pipeline summary with Terraform Cloud-like styling'
inputs:
  plan-summary:
    description: 'JSON summary of plan changes (add, change, destroy, has_changes)'
    required: true
  formatted-plan:
    description: 'Formatted terraform plan output (JSON)'
    required: true
  plan-outcome:
    description: 'Plan outcome (success/failure)'
    required: true
  plan-output:
    description: 'Raw terraform plan output (for error display)'
    required: false
    default: ''
  skip-pr-comment:
    description: 'Skip posting to PR comment (true/false)'
    required: false
    default: 'false'
outputs:
  comment-id:
    description: 'ID of the created or updated PR comment'
    value: ${{ steps.post-pr.outputs.comment-id }}
runs:
  using: composite
  steps:
    - name: Check for pre-written plan data files
      id: check-files
      shell: bash
      env:
        PLAN_OUTCOME: ${{ inputs.plan-outcome }}
      run: |
        # Check if plan data was pre-written by terraform-plan action
        if [ -n "$TERRAFORM_PLAN_DATA_DIR" ] && [ -d "$TERRAFORM_PLAN_DATA_DIR" ]; then
          echo "✅ Using pre-written plan data from: $TERRAFORM_PLAN_DATA_DIR"
          echo "use_prewritten=true" >> $GITHUB_OUTPUT
          echo "data_dir=$TERRAFORM_PLAN_DATA_DIR" >> $GITHUB_OUTPUT

          # Copy to action directory for subsequent steps
          cp "$TERRAFORM_PLAN_DATA_DIR/plan-summary.json" "${{ github.action_path }}/plan-summary.json"
          cp "$TERRAFORM_PLAN_DATA_DIR/formatted-plan.json" "${{ github.action_path }}/formatted-plan.json"

          # Write plan outcome to file (not written by terraform-plan action)
          echo "$PLAN_OUTCOME" > "${{ github.action_path }}/plan-outcome.txt"

          echo "✅ Copied plan data files to action directory"
          ls -lh "${{ github.action_path }}"/*.json "${{ github.action_path }}"/*.txt 2>/dev/null || true
        else
          echo "⚠️  No pre-written plan data found, will write from inputs"
          echo "use_prewritten=false" >> $GITHUB_OUTPUT
        fi

    - name: Save plan data to files
      id: save-data
      if: steps.check-files.outputs.use_prewritten != 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Get inputs
          const planSummary = `${{ inputs.plan-summary }}`;
          const formattedPlan = `${{ inputs.formatted-plan }}`;
          const planOutcome = `${{ inputs.plan-outcome }}`;
          const planOutput = `${{ inputs.plan-output }}`;

          // Define file paths
          const actionPath = '${{ github.action_path }}';
          const summaryPath = path.join(actionPath, 'plan-summary.json');
          const planPath = path.join(actionPath, 'formatted-plan.json');
          const outcomePath = path.join(actionPath, 'plan-outcome.txt');
          const outputPath = path.join(actionPath, 'plan-output.txt');

          // Write files
          fs.writeFileSync(summaryPath, planSummary);
          fs.writeFileSync(planPath, formattedPlan);
          fs.writeFileSync(outcomePath, planOutcome);
          fs.writeFileSync(outputPath, planOutput || '');

          // Log file sizes
          const summarySize = fs.statSync(summaryPath).size;
          const planSize = fs.statSync(planPath).size;
          const outcomeSize = fs.statSync(outcomePath).size;
          const outputSize = fs.statSync(outputPath).size;

          core.info(`✅ Plan data files created`);
          core.info(`  - plan-summary.json: ${summarySize} bytes`);
          core.info(`  - formatted-plan.json: ${planSize} bytes`);
          core.info(`  - plan-outcome.txt: ${outcomeSize} bytes`);
          core.info(`  - plan-output.txt: ${outputSize} bytes`);

    - name: Generate PR Comment
      id: generate-comment
      if: ${{ inputs.skip-pr-comment != 'true' && github.event_name == 'pull_request' }}
      shell: bash
      env:
        PLAN_SUMMARY_PATH: ${{ github.action_path }}/plan-summary.json
        FORMATTED_PLAN_PATH: ${{ github.action_path }}/formatted-plan.json
        PLAN_OUTCOME_PATH: ${{ github.action_path }}/plan-outcome.txt
        PLAN_OUTPUT_PATH: ${{ github.action_path }}/plan-output.txt
        PLAN_OUTCOME: ${{ inputs.plan-outcome }}
      working-directory: ${{ github.action_path }}
      run: ${{ github.action_path }}/generate-pr-comment.sh

    - name: Post to PR
      id: post-pr
      if: ${{ inputs.skip-pr-comment != 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        retries: 3
        script: |
          const fs = require('fs');

          // Read generated comment
          const commentPath = '${{ github.action_path }}/pr-comment.md';
          const commentBody = fs.readFileSync(commentPath, 'utf8');

          // Unique marker for finding this comment
          const COMMENT_MARKER = '<!-- terraform-plan-comment -->';

          core.info('Fetching existing comments...');
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            per_page: 100
          });

          // Find comment by unique marker
          const botComment = comments.find(c => c.body && c.body.includes(COMMENT_MARKER));
          core.info(`Found ${comments.length} comments, ${botComment ? 'updating existing #' + botComment.id : 'creating new'}`);

          let commentId = null;
          try {
            if (botComment) {
              core.info(`Updating comment ${botComment.id}...`);
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
              core.info('Comment updated');
              commentId = botComment.id;
            } else {
              core.info('Creating comment...');
              const result = await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
              core.info(`Comment created: ${result.data.id}`);
              commentId = result.data.id;
            }
            core.notice(`Terraform plan posted to PR #${context.issue.number}`);
          } catch (error) {
            core.error(`Failed: ${error.message}`);
            core.setFailed(error.stack);
            throw error;
          }

          core.setOutput('comment-id', commentId);

    - name: Generate Pipeline Summary
      id: generate-summary
      shell: bash
      env:
        PLAN_SUMMARY_PATH: ${{ github.action_path }}/plan-summary.json
        FORMATTED_PLAN_PATH: ${{ github.action_path }}/formatted-plan.json
        PLAN_OUTCOME_PATH: ${{ github.action_path }}/plan-outcome.txt
        PLAN_OUTPUT_PATH: ${{ github.action_path }}/plan-output.txt
        PLAN_OUTCOME: ${{ inputs.plan-outcome }}
      working-directory: ${{ github.action_path }}
      run: ${{ github.action_path }}/generate-pipeline-summary.sh

    - name: Update pipeline summary
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          // Read generated summary
          const summaryPath = '${{ github.action_path }}/pipeline-summary.md';
          const summaryContent = fs.readFileSync(summaryPath, 'utf8');

          await core.summary
            .addRaw(summaryContent)
            .write();

    - name: Store outputs
      id: outputs
      shell: bash
      env:
        POST_PR_COMMENT_ID: ${{ steps.post-pr.outputs.comment-id }}
      run: bash ${{ github.action_path }}/store-outputs.sh
