name: 'Post Terraform Plan'
description: 'Posts Terraform plan to PR comments and generates pipeline summary'
inputs:
  plan-summary:
    description: 'JSON summary of plan changes (add, change, destroy, has_changes)'
    required: true
  formatted-plan:
    description: 'Formatted terraform plan output'
    required: true
  plan-outcome:
    description: 'Plan outcome (success/failure)'
    required: true
  skip-pr-comment:
    description: 'Skip posting to PR comment (true/false)'
    required: false
    default: 'false'
outputs:
  comment-id:
    description: 'ID of the created or updated PR comment'
    value: ${{ steps.post-pr.outputs.comment-id }}
runs:
  using: composite
  steps:
    - name: Generate plan section
      id: generate-sections
      shell: bash
      run: |
        # Parse inputs
        PLAN_SUMMARY='${{ inputs.plan-summary }}'
        FORMATTED_PLAN='${{ inputs.formatted-plan }}'
        PLAN_OUTCOME='${{ inputs.plan-outcome }}'

        # Write to output file for later steps
        echo "$PLAN_SUMMARY" > ${{ github.action_path }}/plan-summary.json
        echo "$FORMATTED_PLAN" > ${{ github.action_path }}/formatted-plan.txt
        echo "$PLAN_OUTCOME" > ${{ github.action_path }}/plan-outcome.txt

    - name: Post to PR
      id: post-pr
      if: ${{ inputs.skip-pr-comment != 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      env:
        PLAN_SUMMARY: ${{ inputs.plan-summary }}
        FORMATTED_PLAN: ${{ inputs.formatted-plan }}
        PLAN_OUTCOME: ${{ inputs.plan-outcome }}
      with:
        github-token: ${{ github.token }}
        retries: 3
        script: |
          const summary = JSON.parse(process.env.PLAN_SUMMARY || '{"add":0,"change":0,"destroy":0,"has_changes":false}');
          const rawPlan = process.env.FORMATTED_PLAN || 'No plan output available';
          const planOutcome = process.env.PLAN_OUTCOME;

          core.info(`Plan Outcome: ${planOutcome}`);
          core.info(`Summary: Add=${summary.add}, Change=${summary.change}, Destroy=${summary.destroy}`);

          const hasChanges = summary.has_changes;
          const runNumber = context.runNumber;
          const runId = context.runId;
          const runUrl = `${context.payload.repository.html_url}/actions/runs/${runId}`;
          const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';

          // Unique marker for finding this comment - MUST be at the start
          const COMMENT_MARKER = '<!-- terraform-plan-comment -->';

          // Parse resources from terraform plan output
          function parseResources(planOutput) {
            const resources = [];
            const lines = planOutput.split('\n');
            let currentResource = null;
            let currentDetails = [];
            let inResource = false;

            for (const line of lines) {
              const resourceMatch = line.match(/^\s*#\s+(.+?)\s+(will be|must be)\s+(created|updated in-place|replaced|destroyed)/);
              if (resourceMatch) {
                if (currentResource) {
                  resources.push({ ...currentResource, details: currentDetails.join('\n') });
                }
                const actionText = resourceMatch[3];
                let action = 'read';
                if (actionText === 'created') action = 'create';
                else if (actionText === 'updated in-place') action = 'update';
                else if (actionText === 'replaced') action = 'replace';
                else if (actionText === 'destroyed') action = 'destroy';
                currentResource = { address: resourceMatch[1], action };
                currentDetails = [];
                inResource = true;
                continue;
              }

              if (inResource && line.trim()) {
                if (line.match(/^Plan:|^Changes to Outputs:|^Warning:|^-+$/)) {
                  inResource = false;
                  if (currentResource) {
                    resources.push({ ...currentResource, details: currentDetails.join('\n') });
                    currentResource = null;
                    currentDetails = [];
                  }
                } else {
                  currentDetails.push(line);
                }
              }
            }
            if (currentResource) {
              resources.push({ ...currentResource, details: currentDetails.join('\n') });
            }
            return resources;
          }

          const resources = parseResources(rawPlan);
          core.info(`Parsed ${resources.length} resources from plan`);

          const creates = resources.filter(r => r.action === 'create');
          const updates = resources.filter(r => r.action === 'update');
          const replaces = resources.filter(r => r.action === 'replace');
          const destroys = resources.filter(r => r.action === 'destroy');

          function buildResourceSection(resource) {
            const icons = { create: '+', update: '~', replace: '-/+', destroy: '-' };
            const icon = icons[resource.action] || '?';
            const cleanDetails = resource.details.split('\n').filter(l => l.trim()).map(l => l.replace(/^\s{4}/, '')).join('\n');
            return `<details>\n<summary><code>${icon}</code> <code>${resource.address}</code></summary>\n\n\`\`\`hcl\n${cleanDetails || '(no details)'}\n\`\`\`\n\n</details>`;
          }

          // Build the comment body
          const sections = [];

          // Hidden marker for comment detection
          sections.push(COMMENT_MARKER);
          sections.push('');

          // Status header with outcome
          if (planOutcome === 'success') {
            sections.push('## :white_check_mark: Terraform Plan');
          } else {
            sections.push('## :x: Terraform Plan Failed');
          }
          sections.push('');

          // Compact info line with run number prominently displayed
          sections.push(`> **Run #${runNumber}** | ${timestamp} | @${context.actor} | [View Workflow](${runUrl})`);
          sections.push('');

          // Summary section - compact inline badges
          if (hasChanges) {
            const badges = [];
            if (summary.add > 0) badges.push(`:green_circle: **${summary.add}** to add`);
            if (summary.change > 0) badges.push(`:yellow_circle: **${summary.change}** to change`);
            if (summary.destroy > 0) badges.push(`:red_circle: **${summary.destroy}** to destroy`);
            sections.push(`**Plan:** ${badges.join(' · ')}`);
          } else {
            sections.push('**Plan:** :white_check_mark: No changes. Infrastructure is up-to-date.');
          }
          sections.push('');
          sections.push('---');
          sections.push('');

          // Resource details by action type - more compact headers
          if (creates.length > 0) {
            sections.push(`<details open>`);
            sections.push(`<summary><strong>:green_circle: Create (${creates.length})</strong></summary>`);
            sections.push('');
            creates.forEach(r => sections.push(buildResourceSection(r)));
            sections.push('</details>');
            sections.push('');
          }
          if (replaces.length > 0) {
            sections.push(`<details open>`);
            sections.push(`<summary><strong>:purple_circle: Replace (${replaces.length})</strong></summary>`);
            sections.push('');
            replaces.forEach(r => sections.push(buildResourceSection(r)));
            sections.push('</details>');
            sections.push('');
          }
          if (updates.length > 0) {
            sections.push(`<details open>`);
            sections.push(`<summary><strong>:yellow_circle: Update (${updates.length})</strong></summary>`);
            sections.push('');
            updates.forEach(r => sections.push(buildResourceSection(r)));
            sections.push('</details>');
            sections.push('');
          }
          if (destroys.length > 0) {
            sections.push(`<details open>`);
            sections.push(`<summary><strong>:red_circle: Destroy (${destroys.length})</strong></summary>`);
            sections.push('');
            destroys.forEach(r => sections.push(buildResourceSection(r)));
            sections.push('</details>');
            sections.push('');
          }

          // Fallback: show raw plan if no resources parsed but has changes
          if (resources.length === 0 && hasChanges) {
            sections.push('<details>');
            sections.push('<summary><strong>:page_facing_up: Raw Plan Output</strong></summary>');
            sections.push('');
            sections.push('```hcl');
            sections.push(rawPlan.length > 60000 ? rawPlan.substring(0, 60000) + '\n...(truncated)' : rawPlan);
            sections.push('```');
            sections.push('</details>');
            sections.push('');
          }

          const commentBody = sections.join('\n');

          core.info('Fetching comments...');
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            per_page: 100
          });

          // Find comment by unique marker (most reliable method)
          const botComment = comments.find(c => c.body && c.body.includes(COMMENT_MARKER));
          core.info(`Found ${comments.length} comments, ${botComment ? 'updating existing #' + botComment.id : 'creating new'}`);

          let commentId = null;
          try {
            if (botComment) {
              core.info(`Updating comment ${botComment.id}...`);
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
              core.info('Comment updated');
              commentId = botComment.id;
            } else {
              core.info('Creating comment...');
              const result = await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
              core.info(`Comment created: ${result.data.id}`);
              commentId = result.data.id;
            }
            core.notice(`Terraform plan posted to PR #${context.issue.number}`);
          } catch (error) {
            core.error(`Failed: ${error.message}`);
            core.setFailed(error.stack);
            throw error;
          }

          core.setOutput('comment-id', commentId);

    - name: Update pipeline summary
      uses: actions/github-script@v7
      env:
        PLAN_SUMMARY: ${{ inputs.plan-summary }}
        PLAN_OUTCOME: ${{ inputs.plan-outcome }}
      with:
        script: |
          const summary = JSON.parse(process.env.PLAN_SUMMARY || '{"add":0,"change":0,"destroy":0,"has_changes":false}');
          const planOutcome = process.env.PLAN_OUTCOME;
          const hasChanges = summary.has_changes;
          const runNumber = context.runNumber;

          const lines = [];

          // Header
          if (planOutcome === 'success') {
            lines.push('## :white_check_mark: Terraform Plan');
          } else {
            lines.push('## :x: Terraform Plan Failed');
          }
          lines.push('');
          lines.push(`**Run #${runNumber}**`);
          lines.push('');

          // Summary line
          if (hasChanges) {
            const badges = [];
            if (summary.add > 0) badges.push(`:green_circle: **${summary.add}** to add`);
            if (summary.change > 0) badges.push(`:yellow_circle: **${summary.change}** to change`);
            if (summary.destroy > 0) badges.push(`:red_circle: **${summary.destroy}** to destroy`);
            lines.push(badges.join(' · '));
          } else {
            lines.push(':white_check_mark: No changes. Infrastructure is up-to-date.');
          }
          lines.push('');

          await core.summary
            .addRaw(lines.join('\n'))
            .write();

    - name: Store outputs
      id: outputs
      shell: bash
      run: |
        # Store comment-id if available (from PR post step)
        if [ -n "${{ steps.post-pr.outputs.comment-id }}" ]; then
          echo "comment-id=${{ steps.post-pr.outputs.comment-id }}" >> $GITHUB_OUTPUT
        fi
