# Reusable Python setup with uv for test jobs
# Sets up Python, pip/uv cache, and installs dependencies
# Optimized for test jobs that need shared and service-specific packages

name: 'Setup Python with uv'
description: 'Setup Python with uv package manager, caching, and dependency installation'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  shared-package:
    description: 'Install shared package'
    required: false
    default: 'true'
  service-package:
    description: 'Service package path to install (e.g., services/api)'
    required: false
    default: ''
  install-pytest-xdist:
    description: 'Install pytest-xdist for parallel testing'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pip and uv caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/uv
        key: ${{ runner.os }}-pip-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-uv-

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"

    - name: Install shared package
      if: inputs.shared-package == 'true'
      shell: bash
      run: uv pip install --system -e "services/shared[dev]"

    - name: Install service package
      if: inputs.service-package != ''
      shell: bash
      run: uv pip install --system -e "${{ inputs.service-package }}[dev]"

    - name: Install pytest-xdist
      if: inputs.install-pytest-xdist == 'true'
      shell: bash
      run: uv pip install --system pytest-xdist
