name: Close SWA Environment
description: Closes a specific Azure Static Web Apps staging environment by PR number

inputs:
  pr-number:
    description: PR number whose SWA environment should be closed
    required: true
  swa-deployment-token:
    description: Azure Static Web Apps deployment token
    required: true

runs:
  using: composite
  steps:
    - name: "Close SWA environment for PR #${{ inputs.pr-number }}"
      uses: Azure/static-web-apps-deploy@v1
      continue-on-error: true
      with:
        azure_static_web_apps_api_token: ${{ inputs.swa-deployment-token }}
        action: close
