name: 'Create Production Deployment Summary'
description: 'Creates a GitHub Actions step summary for production deployments'
inputs:
  image-tag:
    description: 'Docker image tag deployed'
    required: true
  commit-sha:
    description: 'Git commit SHA'
    required: true
  update-overlay-result:
    description: 'Result of update-overlay job'
    required: true
  deploy-frontend-result:
    description: 'Result of deploy-frontend job'
    required: true
  verify-deployment-result:
    description: 'Result of verify-deployment job'
    required: true
runs:
  using: composite
  steps:
    - name: Generate summary
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.image-tag }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        UPDATE_OVERLAY_RESULT: ${{ inputs.update-overlay-result }}
        DEPLOY_FRONTEND_RESULT: ${{ inputs.deploy-frontend-result }}
        VERIFY_DEPLOYMENT_RESULT: ${{ inputs.verify-deployment-result }}
      run: ${{ github.action_path }}/create-prod-summary.sh
