# Scan JavaScript/TypeScript Dependencies and Quality
# Checks for missing deps, vulnerabilities, and code quality issues
# Uses: npm audit, depcheck, eslint

name: 'Scan JavaScript Dependencies and Quality'
description: 'Scan JavaScript/TypeScript for missing dependencies and security issues'

inputs:
  working-directory:
    description: 'Directory containing package.json (e.g., apps/web)'
    required: true
  check-missing-deps:
    description: 'Check for missing dependencies using depcheck'
    required: false
    default: 'true'
  check-security:
    description: 'Run npm audit for security vulnerabilities'
    required: false
    default: 'true'
  audit-level:
    description: 'Minimum severity level for npm audit (low, moderate, high, critical)'
    required: false
    default: 'high'

runs:
  using: 'composite'
  steps:
    - name: Install scanning tools
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm install -g depcheck

    - name: Check for missing dependencies with depcheck
      if: inputs.check-missing-deps == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "🔍 Scanning for missing JavaScript dependencies..."
        depcheck --ignores="@types/*,eslint-*,prettier,typescript,vitest,playwright" || {
          echo "❌ Missing or unused dependencies detected"
          echo "Review the output above and update package.json"
          exit 1
        }

    - name: Run npm audit for security vulnerabilities
      if: inputs.check-security == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "🔒 Scanning for security vulnerabilities..."
        npm audit --audit-level=${{ inputs.audit-level }} || {
          echo "⚠️  Security vulnerabilities detected"
          echo "Run 'npm audit fix' to resolve issues"
          exit 1
        }

    - name: Verify no missing peer dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "🔍 Checking peer dependencies..."
        npm ls --depth=0 || {
          echo "⚠️  Peer dependency issues detected"
          exit 1
        }

    - name: Summary
      shell: bash
      run: |
        echo "✅ JavaScript dependency scan complete"
